const partnerShowcaseGrid = {
  id: "editorial-01",
  title: "Hormone & Fertility",
  slug: "editorial",
  description: "Goodbody blood test kits for targeted health insights",
  featured: false,
  images: [
    {
      id: "editorial-004",
      src: "/images/female-hormone-fertility.png",
      alt: "Goodbody Female Hormone & Fertility Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Female Hormone & Fertility", profession: "Blood Test" },
      metadata: {
        title: "Female Hormone & Fertility Blood Test",
        year: "",
        description: "A comprehensive test to assess female hormone levels and fertility markers.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-011",
      src: "/images/prenatalsafe-5-nipt.png",
      alt: "Goodbody PrenatalSAFE 5 NIPT Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "PrenatalSAFE 5 NIPT", profession: "Blood Test" },
      metadata: {
        title: "PrenatalSAFE 5 NIPT Blood Test",
        year: "",
        description: "Non-invasive prenatal screening for the five most common chromosomal conditions.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-012",
      src: "/images/testosterone-blood-test.png",
      alt: "Goodbody Testosterone Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Testosterone", profession: "Blood Test" },
      metadata: {
        title: "Testosterone Blood Test",
        year: "",
        description: "Measure your testosterone levels for insight into hormonal health.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-005",
      src: "/images/thyroid-function-blood-test.png",
      alt: "Goodbody Thyroid Function Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Thyroid Function", profession: "Blood Test" },
      metadata: {
        title: "Thyroid Function Blood Test",
        year: "",
        description: "Check your thyroid function to help manage energy, metabolism and overall wellbeing.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-014",
      src: "/images/pregnancy-blood-test.png",
      alt: "Goodbody Pregnancy Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Pregnancy", profession: "Blood Test" },
      metadata: {
        title: "Pregnancy Blood Test",
        year: "",
        description: "A simple at-home blood test to confirm pregnancy.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-008",
      src: "/images/anti-mullerian-hormone.png",
      alt: "Goodbody Anti-Mullerian Hormone Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Anti-Mullerian Hormone", profession: "Blood Test" },
      metadata: {
        title: "Anti-Mullerian Hormone Blood Test",
        year: "",
        description: "Measure your AMH levels for insight into ovarian reserve and fertility.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-009",
      src: "/images/prenatalsafe-complete-plus-nipt.png",
      alt: "Goodbody PrenatalSAFE Complete Plus NIPT Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "PrenatalSAFE Complete Plus NIPT", profession: "Blood Test" },
      metadata: {
        title: "PrenatalSAFE Complete Plus NIPT Blood Test",
        year: "",
        description: "The most comprehensive non-invasive prenatal test available.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-007",
      src: "/images/male-hormone-fertility.png",
      alt: "Goodbody Male Hormone and Fertility Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Male Hormone & Fertility", profession: "Blood Test" },
      metadata: {
        title: "Male Hormone and Fertility Blood Test",
        year: "",
        description: "A comprehensive test to assess male hormone levels and fertility markers.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-013",
      src: "/images/prenatalsafe-3-nipt.png",
      alt: "Goodbody PrenatalSAFE 3 NIPT Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "PrenatalSAFE 3 NIPT", profession: "Blood Test" },
      metadata: {
        title: "PrenatalSAFE 3 NIPT Blood Test",
        year: "",
        description: "Non-invasive prenatal screening for the three most common trisomies.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-001",
      src: "/images/cortisol-stress-blood-test.png",
      alt: "Goodbody Cortisol Stress Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Cortisol Stress", profession: "Blood Test" },
      metadata: {
        title: "Cortisol Stress Blood Test",
        year: "",
        description: "Measure your cortisol levels to understand how stress may be affecting your health.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-010",
      src: "/images/prenatalsafe-karyo-plus-nipt.png",
      alt: "Goodbody PrenatalSAFE Karyo Plus NIPT Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "PrenatalSAFE Karyo Plus NIPT", profession: "Blood Test" },
      metadata: {
        title: "PrenatalSAFE Karyo Plus NIPT Blood Test",
        year: "",
        description: "Advanced non-invasive prenatal screening with karyotype-level detail.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
    {
      id: "editorial-006",
      src: "/images/thyroid-blood-test.png",
      alt: "Goodbody Thyroid Blood Test kit box",
      aspectRatio: 0.8,
      objectFit: "contain",
      caption: { subject: "Thyroid", profession: "Blood Test" },
      metadata: {
        title: "Thyroid Blood Test",
        year: "",
        description: "A focused thyroid blood test to assess your thyroid health.",
        location: "",
        photographer: "",
        photographerUrl: "",
        pexelsUrl: "",
        series: "editorial",
      },
    },
  ],
};
