// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-public
// Bundled from src/lib/mcp/public.ts by @lovable.dev/mcp-js.
// src/lib/mcp/public.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/search-tests.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/shared.ts
import { createClient } from "npm:@supabase/supabase-js@2.111.0";
var PRICE_NOTE = "Prices are the provider's own published prices on the date shown in updated_at and can change. Confirm the final price on the provider's page. For comparison only; not medical advice.";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function fail(message) {
  return {
    content: [{ type: "text", text: `Error: ${message}` }],
    isError: true
  };
}
function escapeLike(value) {
  return value.replace(/\\/g, "\\\\").replace(/%/g, "\\%").replace(/_/g, "\\_");
}
function ilikeContains(keyword) {
  const escaped = escapeLike(keyword).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"%${escaped}%"`;
}
function accreditationStatus(flags) {
  const values = [
    flags.lab_ukas_accredited,
    flags.lab_cqc_regulated,
    flags.lab_iso15189
  ];
  if (values.some((v) => v === false)) return "failed";
  if (flags.lab_ukas_accredited === true && flags.lab_cqc_regulated === true)
    return "confirmed";
  return "not_confirmed";
}
function withAccreditation(row) {
  const flags = {
    lab_ukas_accredited: row.lab_ukas_accredited ?? null,
    lab_cqc_regulated: row.lab_cqc_regulated ?? null,
    lab_iso15189: row.lab_iso15189 ?? null
  };
  return { ...row, ...flags, accreditation_status: accreditationStatus(flags) };
}
function toNumber(value) {
  if (value == null || value === "") return null;
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) ? n : null;
}
function biomarkerNames(list) {
  if (!Array.isArray(list)) return [];
  return list.map((item) => {
    if (typeof item === "string") return item.trim();
    if (item && typeof item === "object" && "name" in item) {
      const name = item.name;
      return typeof name === "string" ? name.trim() : "";
    }
    return "";
  }).filter((s) => s.length > 0);
}

// src/lib/mcp/tools/search-tests.ts
var LISTING_COLUMNS = "id, test_name, provider_id, provider_name, biomarker_count, price, collection_fee_type, collection_fee_amount, clinical_review_type, clinical_review_fee, total_expected_cost, turnaround_days_text, sample_type, collection_method, location_options, home_kit_available, clinic_visit_available, url, lab_ukas_accredited, lab_cqc_regulated, lab_iso15189, updated_at";
var SORTS = {
  price_asc: { column: "total_expected_cost", ascending: true },
  price_desc: { column: "total_expected_cost", ascending: false },
  biomarkers_desc: { column: "biomarker_count", ascending: false },
  name: { column: "test_name", ascending: true }
};
var search_tests_default = defineTool({
  name: "search_tests",
  title: "Search diagnostic tests",
  description: "Search the myhealth checkup catalogue of UK private diagnostic tests. The keyword matches the test name or the provider's description. Filter by category slug (see list_categories), provider, maximum total expected cost, minimum biomarker count and collection method. Sorted only by the sort you choose (default price_asc, by total expected cost). Returns every listing field: name, biomarker count, price, collection and clinical review fees, total expected cost, turnaround, sample type, collection method, location options, home kit and clinic availability, provider URL, accreditation flags with accreditation_status and updated_at, plus total_matches.",
  inputSchema: {
    query: z.string().trim().max(100).optional().describe("Keyword matched against test name or description."),
    category: z.string().trim().optional().describe("Category slug, for example 'womens-health'."),
    provider: z.string().trim().optional().describe("Provider id or name, for example 'medichecks'."),
    max_price: z.number().positive().optional().describe("Maximum total expected cost in GBP."),
    min_biomarkers: z.number().int().min(1).optional(),
    collection: z.enum(["home_kit", "clinic_visit"]).optional(),
    include_addons: z.boolean().default(false).describe("Include add-on tests that cannot be bought alone."),
    sort: z.enum(["price_asc", "price_desc", "biomarkers_desc", "name"]).default("price_asc"),
    limit: z.number().int().min(1).max(50).default(20),
    offset: z.number().int().min(0).default(0)
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (args) => {
    const sort = SORTS[args.sort];
    let q = anonClient().from("unified_provider_tests").select(LISTING_COLUMNS, { count: "exact" });
    if (args.query) {
      const operand = ilikeContains(args.query);
      q = q.or(`test_name.ilike.${operand},description.ilike.${operand}`);
    }
    if (args.category) q = q.eq("category_primary", args.category);
    if (args.provider) {
      const operand = ilikeContains(args.provider);
      q = q.or(`provider_id.ilike.${operand},provider_name.ilike.${operand}`);
    }
    if (args.max_price != null)
      q = q.lte("total_expected_cost", args.max_price);
    if (args.min_biomarkers != null)
      q = q.gte("biomarker_count", args.min_biomarkers);
    if (args.collection === "home_kit") q = q.eq("home_kit_available", true);
    if (args.collection === "clinic_visit")
      q = q.eq("clinic_visit_available", true);
    if (!args.include_addons) q = q.eq("is_addon", false);
    const { data, error, count } = await q.order(sort.column, { ascending: sort.ascending, nullsFirst: false }).order("id", { ascending: true }).range(args.offset, args.offset + args.limit - 1);
    if (error) return fail(error.message);
    return ok({
      total_matches: count ?? 0,
      offset: args.offset,
      sort: args.sort,
      results: (data ?? []).map(
        (r) => withAccreditation(r)
      ),
      note: PRICE_NOTE
    });
  }
});

// src/lib/mcp/tools/get-test.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.24.2";
var TEST_DETAIL_COLUMNS = "id, provider_id, provider_name, test_name, description, is_addon, category_primary, price, original_price, collection_fee_type, collection_fee_amount, clinical_review_type, clinical_review_fee, total_expected_cost, biomarker_count, biomarkers_list, biomarkers_listed, turnaround_days_text, sample_type, collection_method, location_options, home_kit_available, clinic_visit_available, url, url_verified, lab_ukas_accredited, lab_cqc_regulated, lab_iso15189, scraped_at, updated_at";
function testLimitations(t) {
  const out = [];
  const price = toNumber(t.price);
  if (price == null) out.push("Price is missing.");
  else if (price <= 1)
    out.push("Price looks like a placeholder and is unverified.");
  if (toNumber(t.total_expected_cost) == null)
    out.push("Total expected cost has not been calculated.");
  const count = toNumber(t.biomarker_count);
  const listed = toNumber(t.biomarkers_listed);
  if (!listed) out.push("The provider's biomarker list has not been captured.");
  else if (count != null && listed < count)
    out.push(
      `Only ${listed} of ${count} biomarkers are listed by name; the list is incomplete.`
    );
  if (t.url_verified === null)
    out.push("The booking link has not been checked yet.");
  else if (t.url_verified === false)
    out.push("The booking link failed its last check.");
  if (!t.collection_fee_type)
    out.push("Collection fee information has not been captured.");
  if (!t.turnaround_days_text) out.push("Turnaround time is not stated.");
  return out;
}
var get_test_default = defineTool2({
  name: "get_test",
  title: "Get test details",
  description: "Fetch the full record for one test by id: provider description (verbatim), full biomarker list, price, collection and clinical review fees, total expected cost, turnaround, sample and collection method, location options, accreditation flags with accreditation_status (confirmed, not_confirmed or failed), provider URL, scraped_at and updated_at, plus a limitations list stating any missing or unverified data.",
  inputSchema: {
    id: z2.string().uuid().describe("Test UUID returned by search_tests.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ id }) => {
    const { data, error } = await anonClient().from("unified_provider_tests").select(TEST_DETAIL_COLUMNS).eq("id", id).maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Not found");
    const test = data;
    return ok({
      test: withAccreditation(test),
      limitations: testLimitations(test),
      note: PRICE_NOTE
    });
  }
});

// src/lib/mcp/tools/list-providers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
var list_providers_default = defineTool3({
  name: "list_providers",
  title: "List providers",
  description: "List every private diagnostic test provider compared on myhealth checkup. Each provider carries its accreditation flags (lab_ukas_accredited, lab_cqc_regulated, lab_iso15189; null means not yet recorded) and an accreditation_status: confirmed (UKAS and CQC both true), not_confirmed (a flag is not recorded) or failed (a flag is recorded as false). Only treat a provider as accredited when the status is confirmed. Also returns the number of active tests (add-ons excluded, counted exactly) and the latest updated_at date.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const { data, error } = await anonClient().rpc("mcp_list_providers");
    if (error) return fail(error.message);
    const rows = data ?? [];
    const providers = rows.map(
      (row) => withAccreditation({
        provider_id: row.provider_id,
        provider_name: row.provider_name,
        test_count: toNumber(row.test_count) ?? 0,
        lab_ukas_accredited: row.lab_ukas_accredited,
        lab_cqc_regulated: row.lab_cqc_regulated,
        lab_iso15189: row.lab_iso15189,
        updated_at: row.latest_updated_at
      })
    );
    providers.sort((a, b) => b.test_count - a.test_count);
    return ok({ providers });
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "List categories",
  description: "List test category slugs and names with the number of active tests and providers in each. Use these slugs for the category filter in search_tests.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const { data, error } = await anonClient().rpc("mcp_list_categories");
    if (error) return fail(error.message);
    const categories = (data ?? []).map((c) => ({
      slug: c.slug,
      name: c.name,
      active_tests: toNumber(c.active_tests) ?? 0,
      providers: toNumber(c.providers) ?? 0
    }));
    return ok({ categories });
  }
});

// src/lib/mcp/tools/get-provider.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.24.2";
var get_provider_default = defineTool5({
  name: "get_provider",
  title: "Get provider",
  description: "Profile for one provider: name, accreditation flags with accreditation_status (confirmed, not_confirmed or failed; only confirmed means UKAS and CQC are both recorded as true), number of active tests, home kit and clinic collection options, location options, typical (median) phlebotomy and GP review fees, and the latest updated_at date.",
  inputSchema: {
    provider_id: z3.string().trim().min(1).max(100).describe("Provider id from list_providers, for example 'randox'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ provider_id }) => {
    const { data, error } = await anonClient().rpc("mcp_get_provider", {
      p_provider_id: provider_id
    });
    if (error) return fail(error.message);
    if (!data) return fail("Provider not found.");
    const provider = data;
    return ok({ provider: withAccreditation(provider), note: PRICE_NOTE });
  }
});

// src/lib/mcp/tools/compare-tests.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.24.2";
function biomarkerOverlap(tests) {
  const sets = tests.map((t) => ({
    id: t.id,
    map: new Map(t.biomarkers.map((b) => [b.toLowerCase(), b]))
  }));
  const shared = sets.length === 0 ? [] : [...sets[0].map.entries()].filter(([key]) => sets.every((s) => s.map.has(key))).map(([, label]) => label);
  const unique = {};
  for (const s of sets) {
    unique[s.id] = [...s.map.entries()].filter(([key]) => sets.every((o) => o.id === s.id || !o.map.has(key))).map(([, label]) => label);
  }
  return { shared, unique };
}
var compare_tests_default = defineTool6({
  name: "compare_tests",
  title: "Compare tests side by side",
  description: "Compare two to five tests by id side by side: price, collection fee, clinical review fee, total expected cost, turnaround, sample method, location options and biomarker counts, plus biomarkers shared by all tests and biomarkers unique to each. Tests are returned in the order given; nothing is ranked.",
  inputSchema: {
    test_ids: z4.array(z4.string().uuid()).min(2).max(5)
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ test_ids }) => {
    const ids = [...new Set(test_ids)];
    if (ids.length < 2) return fail("Provide at least two different test ids.");
    const { data, error } = await anonClient().from("unified_provider_tests").select(
      "id, test_name, provider_name, price, collection_fee_type, collection_fee_amount, clinical_review_type, clinical_review_fee, total_expected_cost, turnaround_days_text, sample_type, collection_method, location_options, biomarker_count, biomarkers_list, lab_ukas_accredited, lab_cqc_regulated, lab_iso15189, updated_at"
    ).in("id", ids);
    if (error) return fail(error.message);
    const byId = new Map((data ?? []).map((r) => [r.id, r]));
    const missing = ids.filter((id) => !byId.has(id));
    if (missing.length > 0)
      return fail(`Tests not found: ${missing.join(", ")}`);
    const ordered = ids.map((id) => byId.get(id));
    const overlap = biomarkerOverlap(
      ordered.map((r) => ({
        id: r.id,
        biomarkers: biomarkerNames(r.biomarkers_list)
      }))
    );
    const table = ordered.map(
      ({ biomarkers_list, ...rest }) => withAccreditation({
        ...rest,
        biomarkers_listed: biomarkerNames(biomarkers_list).length
      })
    );
    return ok({
      tests: table,
      shared_biomarkers: overlap.shared,
      unique_biomarkers: overlap.unique,
      note: PRICE_NOTE
    });
  }
});

// src/lib/mcp/tools/find-tests-by-biomarker.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.24.2";
var find_tests_by_biomarker_default = defineTool7({
  name: "find_tests_by_biomarker",
  title: "Find tests by biomarker",
  description: "Find tests whose biomarker list includes a biomarker name (case-insensitive, partial matches included and shown in matched_biomarkers), sorted by total expected cost from lowest. Add-on tests are excluded.",
  inputSchema: {
    biomarker: z5.string().trim().min(2).max(100).describe("Biomarker name, for example 'ferritin' or 'HbA1c'."),
    max_price: z5.number().positive().optional().describe("Maximum total expected cost in GBP."),
    limit: z5.number().int().min(1).max(100).default(25)
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ biomarker, max_price, limit }) => {
    const { data, error } = await anonClient().rpc(
      "mcp_find_tests_by_biomarker",
      {
        p_name: biomarker,
        p_max_price: max_price ?? null,
        p_limit: limit
      }
    );
    if (error) return fail(error.message);
    const result = data ?? { total_matches: 0, tests: [] };
    const tests = result.tests ?? [];
    const providerIds = [
      ...new Set(
        tests.map((t) => t.provider_id).filter((p) => !!p)
      )
    ];
    const flagsByProvider = /* @__PURE__ */ new Map();
    if (providerIds.length > 0) {
      const { data: provs, error: pErr } = await anonClient().rpc("mcp_list_providers");
      if (pErr) return fail(pErr.message);
      for (const p of provs ?? [])
        flagsByProvider.set(p.provider_id, p);
    }
    return ok({
      biomarker,
      total_matches: result.total_matches ?? 0,
      tests: tests.map((t) => {
        const f = t.provider_id ? flagsByProvider.get(t.provider_id) : void 0;
        return withAccreditation({
          ...t,
          lab_ukas_accredited: f?.lab_ukas_accredited ?? null,
          lab_cqc_regulated: f?.lab_cqc_regulated ?? null,
          lab_iso15189: f?.lab_iso15189 ?? null
        });
      }),
      note: PRICE_NOTE
    });
  }
});

// src/lib/mcp/rate-limit.ts
var PUBLIC_RATE_LIMIT = 60;
var PUBLIC_RATE_WINDOW_MS = 6e4;
function createRateLimiter(limit = PUBLIC_RATE_LIMIT, windowMs = PUBLIC_RATE_WINDOW_MS) {
  const buckets = /* @__PURE__ */ new Map();
  const sweep = (now) => {
    for (const [key, b] of buckets) {
      if (now - b.windowStart >= windowMs) buckets.delete(key);
    }
  };
  return {
    check: (key, now = Date.now()) => {
      if (buckets.size > 1e4) sweep(now);
      const existing = buckets.get(key);
      if (!existing || now - existing.windowStart >= windowMs) {
        buckets.set(key, { count: 1, windowStart: now });
        return { allowed: true, retryAfterSeconds: 0 };
      }
      existing.count += 1;
      if (existing.count > limit) {
        const retry = Math.max(1, Math.ceil((existing.windowStart + windowMs - now) / 1e3));
        return { allowed: false, retryAfterSeconds: retry };
      }
      return { allowed: true, retryAfterSeconds: 0 };
    },
    size: () => buckets.size
  };
}
function clientIp(headers) {
  const cf = headers.get("cf-connecting-ip")?.trim();
  if (cf) return cf;
  const xff = headers.get("x-forwarded-for");
  const first = xff?.split(",")[0]?.trim();
  if (first) return first;
  return headers.get("x-real-ip")?.trim() || "unknown";
}
function withRateLimit(handler, limiter = createRateLimiter()) {
  return (request) => {
    if (request.method === "OPTIONS") return handler(request);
    const { allowed, retryAfterSeconds } = limiter.check(clientIp(request.headers));
    if (!allowed) {
      return new Response(
        JSON.stringify({ error: "Too many requests. Limit is 60 per minute per IP address." }),
        {
          status: 429,
          headers: {
            "content-type": "application/json",
            "retry-after": String(retryAfterSeconds),
            "access-control-allow-origin": "*"
          }
        }
      );
    }
    return handler(request);
  };
}
function installDenoServeRateLimit(target = globalThis) {
  const deno = target.Deno;
  if (!deno || typeof deno.serve !== "function") return false;
  const original = deno.serve.bind(deno);
  const limiter = createRateLimiter();
  deno.serve = (handler) => original(withRateLimit(handler, limiter));
  return true;
}

// src/lib/mcp/public.ts
installDenoServeRateLimit();
var PUBLIC_TOOLS = [
  search_tests_default,
  get_test_default,
  list_providers_default,
  list_categories_default,
  get_provider_default,
  compare_tests_default,
  find_tests_by_biomarker_default
];
var public_default = defineMcp({
  name: "myhealth-checkup-public-mcp",
  title: "myhealth checkup (public catalogue)",
  version: "0.1.0",
  instructions: "Public, read-only tools for myhealth checkup, the UK private diagnostics comparison platform. No sign-in needed. Use search_tests, get_test, compare_tests, find_tests_by_biomarker, list_categories, list_providers and get_provider to compare private blood tests and cancer screening across every listed provider. Each provider and test carries its accreditation flags and an accreditation_status (confirmed, not_confirmed or failed); only describe a provider as accredited when the status is confirmed. Prices are in GBP and turnaround is in days. Rules: prices are provider-published and can change, so always show the updated_at date alongside any price. Never rank or recommend a provider on commercial grounds; order only by the criteria the user asks for. Disclose affiliate relationships where present. Do not imply any NHS integration. State that results are for comparison only and are not medical advice. Requests are limited to 60 per minute per IP address.",
  tools: PUBLIC_TOOLS
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(public_default, { functionName: "mcp-public" }));
