// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-tests.ts
import { createClient } from "npm:@supabase/supabase-js@^2.51.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_tests_default = defineTool({
  name: "search_tests",
  title: "Search diagnostic tests",
  description: "Search the myhealth checkup catalogue of private UK diagnostic tests. Filter by keyword, category, provider, and price. Returns test name, provider, price (GBP), turnaround, biomarker count, and URL.",
  inputSchema: {
    query: z.string().trim().optional().describe("Keyword to match against test name or description."),
    category: z.string().trim().optional().describe("Category slug (e.g. 'womens-health', 'cancer-screening', 'hormones')."),
    provider: z.string().trim().optional().describe("Provider name (e.g. 'Medichecks', 'Randox', 'Goodbody')."),
    max_price: z.number().positive().optional().describe("Maximum total expected cost in GBP."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, provider, max_price, limit }) => {
    let q = anonClient().from("unified_provider_tests").select(
      "id, test_name, provider_name, price, total_expected_cost, category_primary, biomarker_count, turnaround_days_text, sample_type, url"
    ).limit(limit);
    if (query) q = q.ilike("test_name", `%${query}%`);
    if (category) q = q.eq("category_primary", category);
    if (provider) q = q.ilike("provider_name", `%${provider}%`);
    if (max_price != null) q = q.lte("total_expected_cost", max_price);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-test.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.51.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_test_default = defineTool2({
  name: "get_test",
  title: "Get test details",
  description: "Fetch the full record for a single diagnostic test by id, including biomarker list, fees, sample method and booking URL.",
  inputSchema: {
    id: z2.string().uuid().describe("Test UUID returned by search_tests.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await anonClient2().from("unified_provider_tests").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { test: data }
    };
  }
});

// src/lib/mcp/tools/list-providers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.51.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_providers_default = defineTool3({
  name: "list_providers",
  title: "List providers",
  description: "List all UKAS-accredited, CQC-regulated private diagnostic test providers compared on myhealth checkup, with the number of active tests each has.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await anonClient3().from("unified_provider_tests").select("provider_id, provider_name");
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const key = row.provider_id ?? row.provider_name ?? "unknown";
      const existing = counts.get(key);
      if (existing) existing.test_count += 1;
      else counts.set(key, { provider_id: row.provider_id, provider_name: row.provider_name, test_count: 1 });
    }
    const providers = [...counts.values()].sort((a, b) => b.test_count - a.test_count);
    return {
      content: [{ type: "text", text: JSON.stringify(providers, null, 2) }],
      structuredContent: { providers }
    };
  }
});

// src/lib/mcp/tools/list-my-favourites.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.51.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_favourites_default = defineTool4({
  name: "list_my_favourites",
  title: "List my saved tests",
  description: "Return the diagnostic tests the signed-in user has saved to their favourites on myhealth checkup.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient(ctx).from("favorites").select("id, test_id, name, provider, category, price, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favourites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-favourite.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.51.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_favourite_default = defineTool5({
  name: "save_favourite",
  title: "Save a test to my favourites",
  description: "Save a diagnostic test to the signed-in user's favourites on myhealth checkup.",
  inputSchema: {
    test_id: z3.string().min(1).describe("Test id (uuid from search_tests, or provider slug)."),
    name: z3.string().min(1).describe("Test name."),
    provider: z3.string().min(1).describe("Provider name."),
    category: z3.string().optional(),
    price: z3.number().nonnegative().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ test_id, name, provider, category, price }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient2(ctx).from("favorites").insert({ user_id: ctx.getUserId(), test_id, name, provider, category, price }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${name}" to favourites.` }],
      structuredContent: { favourite: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "clvuioagsgfadynuvodj";
var mcp_default = defineMcp({
  name: "myhealth-checkup-mcp",
  title: "myhealth checkup",
  version: "0.1.0",
  instructions: "Tools for myhealth checkup \u2014 the UK private diagnostics comparison platform. Use search_tests and get_test to compare private blood tests and cancer screening across UKAS-accredited, CQC-regulated providers (prices in GBP, turnaround in days). list_providers enumerates partner labs. list_my_favourites and save_favourite act on the signed-in user's saved tests. This platform is decision infrastructure only \u2014 never present results as medical advice or diagnosis.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_tests_default, get_test_default, list_providers_default, list_my_favourites_default, save_favourite_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
