
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, normal_range_male, normal_range_female, clinical_significance, interpretation_guide, lifestyle_factors, related_conditions)
VALUES
-- 1. AMH
('Anti-Müllerian Hormone', 'AMH', 'Fertility', 'AMH is produced by granulosa cells of ovarian follicles and by Sertoli cells in testes. In women, higher AMH generally reflects a larger pool of developing follicles.', 'pmol/L', 'Age and lab specific', 'Age and lab specific; declines with age, very low after menopause', 'Marker of ovarian reserve in women and testicular function in infants.', '{"low": "Low AMH suggests reduced ovarian reserve and may be seen with age, premature ovarian insufficiency or after some cancer treatments.", "high": "High AMH can be seen in polycystic ovary syndrome (PCOS) due to increased small follicles.", "urgent": "Acute pelvic pain, heavy bleeding or suspected ectopic pregnancy require urgent assessment; AMH itself is not an emergency test.", "improve": "Fertility specialists use AMH to guide expectations about response to fertility treatment and to counsel on family-planning options; lifestyle support (weight, smoking, alcohol) helps general reproductive health."}', ARRAY['Weight management', 'Smoking cessation', 'Alcohol reduction', 'Healthy diet'], ARRAY['Premature ovarian insufficiency', 'Polycystic ovary syndrome', 'Diminished ovarian reserve', 'Infertility']),

-- 2. Inhibin B
('Inhibin B', 'INHB', 'Fertility', 'Inhibin B is produced by ovarian follicles in women and by Sertoli cells in testes in men. It is involved in feedback control of FSH.', 'pg/mL', 'Varies by age and assay', 'Varies by age, cycle stage and assay', 'Marker of ovarian function and spermatogenesis used in fertility assessment.', '{"low": "Low levels can suggest reduced ovarian reserve in women or impaired sperm production in men.", "high": "High levels are less common but may be seen in some ovarian tumours and early puberty states.", "urgent": "Lumps in testes, severe pelvic pain or rapid hormonal changes should be evaluated promptly.", "improve": "Fertility and endocrine specialists interpret inhibin B with AMH, FSH and imaging to guide diagnosis and treatment choices."}', ARRAY['Weight management', 'Healthy diet', 'Avoiding toxins'], ARRAY['Reduced ovarian reserve', 'Impaired spermatogenesis', 'Ovarian tumours', 'Premature ovarian insufficiency']),

-- 3. Chromogranin A
('Chromogranin A', 'CGA', 'Cancer Markers', 'Chromogranin A is a protein stored in secretory granules of neuroendocrine cells and released into the bloodstream.', 'µg/L', 'Lab specific', 'Lab specific', 'Marker used in the assessment and monitoring of neuroendocrine tumours.', '{"low": "Normal levels make active neuroendocrine tumours less likely but do not fully exclude them.", "high": "Raised levels can indicate neuroendocrine tumours, but also occur with proton pump inhibitors, renal impairment and other conditions.", "urgent": "Severe flushing, diarrhoea, weight loss or abdominal pain should be assessed urgently.", "improve": "Specialists use chromogranin A alongside imaging and other markers to diagnose and monitor neuroendocrine tumours and to guide surgery and medical therapy."}', ARRAY['Medication review (PPIs can raise levels)'], ARRAY['Neuroendocrine tumours', 'Carcinoid syndrome', 'Phaeochromocytoma']),

-- 4. Gastrin
('Gastrin', 'GAST', 'Digestive', 'Produced by G-cells in the stomach, gastrin increases gastric acid secretion and mucosal growth.', 'pmol/L', 'Fasting; lab specific', 'Fasting; lab specific', 'Hormone that stimulates stomach acid production; used to investigate recurrent ulcers and gastrinoma.', '{"low": "Low levels are usually not clinically important and can be seen with high stomach acid or some medications.", "high": "Raised gastrin can occur with proton pump inhibitor use, atrophic gastritis and gastrin-secreting tumours (Zollinger–Ellison syndrome).", "urgent": "Severe abdominal pain, recurrent ulcers, vomiting blood or black stools need urgent review.", "improve": "Further testing (including gastric pH and imaging) distinguishes drug-related changes from gastrinoma; management may involve adjusting medication, surgery or somatostatin analogues."}', ARRAY['Medication review (PPIs affect levels)', 'Dietary management'], ARRAY['Zollinger-Ellison syndrome', 'Atrophic gastritis', 'Peptic ulcer disease']),

-- 5. Calcitonin
('Calcitonin', 'CALC', 'Thyroid', 'Produced by thyroid C-cells, calcitonin lowers blood calcium by inhibiting bone resorption.', 'pg/mL', 'Low levels; sex and lab specific', 'Low levels; sex and lab specific', 'Tumour marker for medullary thyroid cancer and involved in calcium homeostasis.', '{"low": "Low or undetectable calcitonin is normal and usually not a concern.", "high": "Raised calcitonin can suggest medullary thyroid carcinoma or C-cell hyperplasia and may also be influenced by kidney disease and some medications.", "urgent": "Rapidly growing neck lumps, breathing difficulty or swallowing problems need urgent assessment.", "improve": "Endocrine and surgical teams use calcitonin with imaging and biopsy to diagnose and monitor medullary thyroid cancer and plan surgery or other treatment."}', ARRAY['Regular thyroid monitoring'], ARRAY['Medullary thyroid carcinoma', 'C-cell hyperplasia', 'Multiple endocrine neoplasia']),

-- 6. Plasma Metanephrines
('Plasma Metanephrines', 'METAN', 'Hormones', 'Metanephrine and normetanephrine are breakdown products of adrenaline and noradrenaline produced when catecholamines are metabolised.', 'nmol/L', 'Age specific; lab specific', 'Age specific; lab specific', 'Used to detect phaeochromocytoma and paraganglioma.', '{"low": "Normal levels make catecholamine-secreting tumours less likely.", "high": "Raised levels suggest phaeochromocytoma or paraganglioma and can cause episodes of severe hypertension, palpitations and headaches.", "urgent": "Sudden severe headache, palpitations, chest pain or very high blood pressure are emergencies.", "improve": "Endocrinologists arrange confirmatory tests and imaging; treatment usually involves alpha-blockade then surgery, managed in specialist centres."}', ARRAY['Stress management', 'Medication review'], ARRAY['Phaeochromocytoma', 'Paraganglioma', 'Secondary hypertension']),

-- 7. TRAb
('TSH-Receptor Antibodies', 'TRAB', 'Thyroid', 'TRAb bind to the TSH receptor on thyroid cells and can cause overproduction of thyroid hormone.', 'IU/L', 'Negative/below threshold', 'Negative/below threshold', 'Key autoantibody in Graves'' disease diagnosis and monitoring.', '{"low": "Negative results make Graves'' disease less likely but do not fully exclude it.", "high": "Positive TRAb strongly support Graves'' disease and can predict risk of relapse after treatment.", "urgent": "Severe hyperthyroid symptoms (chest pain, palpitations, breathlessness) need urgent care.", "improve": "Endocrinologists use TRAb to guide therapy (antithyroid drugs, radioiodine, surgery) and monitor disease activity."}', ARRAY['Stress management', 'Smoking cessation'], ARRAY['Graves'' disease', 'Hyperthyroidism', 'Thyroid eye disease']),

-- 8. Adiponectin
('Adiponectin', 'ADPN', 'Metabolic', 'Adiponectin is produced by fat cells and has anti-inflammatory and insulin-sensitising effects.', 'µg/mL', 'Assay specific; influenced by sex and body fat', 'Assay specific; influenced by sex and body fat', 'Adipokine linked with insulin sensitivity and cardiometabolic risk.', '{"low": "Low levels are associated with obesity, insulin resistance, type 2 diabetes and higher cardiovascular risk.", "high": "Higher levels are generally associated with more favourable metabolic profiles, though very high values can appear in some chronic diseases.", "urgent": "Acute metabolic emergencies (e.g. ketoacidosis, chest pain) require urgent care; adiponectin is a long-term risk marker, not an emergency test.", "improve": "Weight loss, regular exercise, improved diet and better insulin sensitivity are associated with higher adiponectin."}', ARRAY['Weight management', 'Regular exercise', 'Healthy diet', 'Smoking cessation'], ARRAY['Obesity', 'Insulin resistance', 'Type 2 diabetes', 'Cardiovascular disease']),

-- 9. Resistin
('Resistin', 'RSTN', 'Metabolic', 'Resistin is produced by adipose tissue and immune cells and may contribute to metabolic and inflammatory processes.', 'ng/mL', 'Research assay specific', 'Research assay specific', 'Adipokine linked to inflammation and insulin resistance.', '{"low": "Lower levels may be associated with lower inflammation and better metabolic health.", "high": "Higher levels have been linked to insulin resistance, obesity and cardiovascular risk in some studies.", "urgent": "Resistin is not used for acute care; urgent symptoms are managed according to clinical presentation.", "improve": "Lifestyle changes that reduce adiposity and inflammation (healthy diet, physical activity, smoking cessation) are likely beneficial."}', ARRAY['Weight management', 'Regular exercise', 'Healthy diet', 'Smoking cessation'], ARRAY['Obesity', 'Insulin resistance', 'Chronic inflammation', 'Cardiovascular disease']),

-- 10. Visfatin
('Visfatin', 'VISF', 'Metabolic', 'Visfatin is produced by visceral fat and may influence glucose metabolism and inflammation.', 'ng/mL', 'Research assay specific', 'Research assay specific', 'Adipokine associated with obesity and metabolic disorders.', '{"low": "The clinical significance of low levels is less clear and mainly studied in research contexts.", "high": "Elevated levels have been associated with obesity, insulin resistance and inflammatory markers.", "urgent": "Visfatin itself is not an emergency marker; acute symptoms should be managed via usual clinical pathways.", "improve": "Weight loss, improved diet and physical activity can help improve overall metabolic health and may reduce unfavourable adipokine profiles."}', ARRAY['Weight management', 'Regular exercise', 'Healthy diet'], ARRAY['Obesity', 'Insulin resistance', 'Metabolic syndrome']),

-- 11. Adropin
('Adropin', 'ADRP', 'Metabolic', 'Adropin may influence glucose and lipid metabolism and endothelial function.', 'ng/mL', 'Research assay dependent', 'Research assay dependent', 'Peptide hormone involved in energy homeostasis and cardiovascular health.', '{"low": "Lower levels have been associated with adverse metabolic markers such as higher HbA1c and fasting glucose.", "high": "Higher levels may be linked with more favourable metabolic profiles, though research is ongoing.", "urgent": "Adropin is not used in acute care; emergency symptoms should be managed conventionally.", "improve": "Evidence suggests that improving metabolic health through diet, exercise and weight management may beneficially influence adropin levels."}', ARRAY['Regular exercise', 'Healthy diet', 'Weight management'], ARRAY['Insulin resistance', 'Type 2 diabetes', 'Cardiovascular disease']),

-- 12. Beta-Hydroxybutyrate
('Beta-Hydroxybutyrate', 'BHB', 'Metabolic', 'BHB is a ketone body produced when the body burns fat for energy during low carbohydrate availability, fasting or insulin deficiency.', 'mmol/L', 'Low in fed states; moderate in nutritional ketosis', 'Low in fed states; moderate in nutritional ketosis', 'Ketone body used to assess ketosis and diabetic ketoacidosis.', '{"low": "Low levels are expected in people eating regular carbohydrate-containing diets.", "high": "High levels can indicate diabetic ketoacidosis, alcoholic ketoacidosis or starvation ketosis.", "urgent": "Symptoms such as nausea, vomiting, abdominal pain, rapid breathing and drowsiness in people with high BHB require emergency care.", "improve": "Treatment includes IV fluids, insulin (for DKA), electrolyte correction and addressing underlying triggers in hospital."}', ARRAY['Blood sugar management', 'Adequate carbohydrate intake', 'Insulin compliance'], ARRAY['Diabetic ketoacidosis', 'Alcoholic ketoacidosis', 'Starvation ketosis', 'Type 1 diabetes']),

-- 13. Acetoacetate
('Acetoacetate', 'ACAC', 'Metabolic', 'Acetoacetate is produced in the liver during fat metabolism and can convert into BHB and acetone.', 'mmol/L', 'Very low normally', 'Very low normally', 'Ketone body measured in blood or urine to assess ketosis.', '{"low": "Low or negative readings are typical outside ketosis.", "high": "High levels occur in ketosis and ketoacidosis and are used alongside clinical assessment.", "urgent": "Suspected ketoacidosis is an emergency.", "improve": "Management mirrors that for high BHB, focusing on DKA or other causes of acidosis."}', ARRAY['Blood sugar management', 'Adequate nutrition', 'Insulin compliance'], ARRAY['Diabetic ketoacidosis', 'Starvation ketosis', 'Alcoholic ketoacidosis']),

-- 14. LDH-1
('LDH-1 Isoenzyme', 'LDH1', 'Cardiovascular', 'LDH exists in several isoenzymes; LDH-1 predominates in heart and red blood cells.', 'U/L', 'Characteristic distribution with LDH-2 slightly higher than LDH-1', 'Characteristic distribution with LDH-2 slightly higher than LDH-1', 'Isoenzyme historically used in cardiac assessment; largely replaced by troponin.', '{"low": "Normal isoenzyme patterns are expected in healthy individuals.", "high": "Raised LDH-1, particularly when higher than LDH-2, may indicate myocardial injury or haemolysis, though troponin has largely replaced it in cardiac diagnosis.", "urgent": "Suspected heart attack or haemolytic crisis needs urgent care regardless of LDH patterns.", "improve": "Treatment focuses on underlying heart or haemolytic disease; isoenzymes are now mainly of historical or specialist interest."}', ARRAY['Heart-healthy lifestyle', 'Regular exercise'], ARRAY['Myocardial infarction', 'Haemolytic anaemia', 'Cardiac injury']),

-- 15. Apolipoprotein(a)
('Apolipoprotein(a)', 'APO_A', 'Cardiovascular', 'Apo(a) forms part of lipoprotein(a) particles. It is a protein attached to an LDL-like particle, forming Lp(a), which promotes atherothrombosis.', 'mg/dL or nmol/L', 'Higher levels associated with greater cardiovascular risk', 'Higher levels associated with greater cardiovascular risk', 'Genetically determined cardiovascular risk factor.', '{"low": "Low levels are favourable and associated with lower inherited risk of atherosclerotic disease.", "high": "High levels are linked to increased risk of coronary heart disease and stroke, independent of other lipids.", "urgent": "Cardiovascular emergencies are managed acutely; apo(a) is a long-term risk marker.", "improve": "While levels themselves are largely genetic, overall cardiovascular risk can be lowered by aggressive management of LDL-C, blood pressure, smoking and diabetes."}', ARRAY['LDL-C management', 'Blood pressure control', 'Smoking cessation', 'Diabetes management'], ARRAY['Coronary heart disease', 'Stroke', 'Peripheral arterial disease', 'Aortic stenosis']),

-- 16. Kappa Free Light Chains
('Serum Free Light Chains (Kappa)', 'FLC_K', 'Immunology', 'Kappa free light chains are unbound light-chain proteins produced by plasma cells and measured alongside lambda chains.', 'mg/L', 'Assay specific', 'Assay specific', 'Used to detect and monitor plasma-cell disorders including myeloma.', '{"low": "Low levels are usually not significant on their own.", "high": "High kappa chains can signal monoclonal gammopathy, myeloma or light-chain amyloidosis when the kappa/lambda ratio is abnormal.", "urgent": "Bone pain, kidney impairment, recurrent infections or anaemia with abnormal FLCs need urgent specialist assessment.", "improve": "Haematologists interpret FLC results with electrophoresis and marrow tests and then treat underlying plasma-cell disorders."}', ARRAY['Regular monitoring'], ARRAY['Multiple myeloma', 'Monoclonal gammopathy', 'Light-chain amyloidosis', 'Waldenström macroglobulinaemia']),

-- 17. Lambda Free Light Chains
('Serum Free Light Chains (Lambda)', 'FLC_L', 'Immunology', 'Lambda free light chains are unbound lambda light-chain fragments in blood, the counterpart to kappa chains.', 'mg/L', 'Assay specific', 'Assay specific', 'Used alongside kappa chains to detect plasma-cell disorders.', '{"low": "Low values are not usually clinically important.", "high": "Raised lambda with an abnormal kappa/lambda ratio suggests lambda-restricted plasma-cell disorders.", "urgent": "Symptoms of myeloma or amyloidosis require early evaluation.", "improve": "Management is guided by haematology teams as part of plasma-cell disorder work-up and treatment."}', ARRAY['Regular monitoring'], ARRAY['Multiple myeloma', 'Light-chain amyloidosis', 'Monoclonal gammopathy']),

-- 18. Kappa/Lambda Ratio
('Kappa/Lambda Free Light Chain Ratio', 'FLC_RATIO', 'Immunology', 'The kappa/lambda ratio compares concentrations of kappa to lambda free light chains; normal ratios indicate polyclonal production.', 'Ratio', '0.26–1.65 (assay dependent)', '0.26–1.65 (assay dependent)', 'Identifies clonality in plasma-cell disorders.', '{"low": "Low ratios suggest excess lambda chains and possible lambda-type monoclonal gammopathy.", "high": "High ratios suggest kappa-dominant monoclonal production.", "urgent": "Symptoms of myeloma or amyloidosis need prompt assessment.", "improve": "Further tests (serum electrophoresis, bone marrow biopsy, imaging) guide diagnosis and treatment of monoclonal gammopathies."}', ARRAY['Regular monitoring'], ARRAY['Multiple myeloma', 'Monoclonal gammopathy', 'Light-chain amyloidosis', 'Waldenström macroglobulinaemia']),

-- 19. 2-hour OGTT Glucose
('2-Hour Plasma Glucose (OGTT)', 'OGTT_2H', 'Diabetes', 'After fasting, a standard glucose load is given, and blood sugar is measured 2 hours later.', 'mmol/L', '<7.8 normal; 7.8–11.0 impaired; ≥11.1 diabetes', '<7.8 normal; 7.8–11.0 impaired; ≥11.1 diabetes', 'Diagnostic test for diabetes and impaired glucose tolerance.', '{"low": "Low values may indicate reactive hypoglycaemia in some contexts.", "high": "High values indicate impaired glucose handling or diabetes and increased risk of complications.", "urgent": "Acute hyperglycaemia with ketones, vomiting or confusion is an emergency.", "improve": "Lifestyle interventions (diet, exercise, weight loss) and, if needed, medications are used to prevent or treat diabetes."}', ARRAY['Healthy diet', 'Regular exercise', 'Weight management', 'Reduced sugar intake'], ARRAY['Type 2 diabetes', 'Impaired glucose tolerance', 'Gestational diabetes', 'Metabolic syndrome']),

-- 20. Anti-Phospholipid Antibodies
('Anti-Phospholipid Antibodies', 'APL', 'Immunology', 'Anti-phospholipid antibodies include anticardiolipin antibodies, anti-β2-glycoprotein I and lupus anticoagulant.', 'Various (GPL, MPL, ratio)', 'Negative/below threshold', 'Negative/below threshold', 'Associated with clotting and pregnancy complications in antiphospholipid syndrome.', '{"low": "Negative results reduce the likelihood of APS but must be interpreted with clinical history.", "high": "Persistently positive aPL with thrombosis or pregnancy loss supports APS diagnosis.", "urgent": "New blood clots, strokes, or pregnancy complications require urgent specialist assessment.", "improve": "Management can include long-term anticoagulation, low-dose aspirin and specialist obstetric care during pregnancy."}', ARRAY['Anticoagulation compliance', 'Regular monitoring'], ARRAY['Antiphospholipid syndrome', 'Deep vein thrombosis', 'Pulmonary embolism', 'Recurrent pregnancy loss', 'Stroke']);
