-- RECONCILIATION MARKER — NON-EXECUTING
-- Version:        20260813135838
-- Class:          H — scheduled job (pg_cron)
-- Statements md5: bf047b1eb727f66dbf3292214063d417
--   (md5 of array_to_string(statements, E';\n') as recorded in
--    supabase_migrations.schema_migrations for this version)
--
-- This migration was applied to production through the Lovable migration tool
-- and was never written back as a file. That is the historical drift recorded in
-- docs/MIGRATION_RECONCILIATION.md.
--
-- This file exists so the repository's migration set matches the applied set and
-- CI parity can detect NEW drift. It deliberately contains no executable SQL:
-- the change is already applied, and replaying historical DDL/DML against a
-- moved-on production database would be harmful.
--
-- The authoritative verbatim body is retained in
--   supabase_migrations.schema_migrations.statements WHERE version = '20260813135838'
-- and can be verified against the md5 above. No SQL has been invented,
-- reconstructed or paraphrased here.
