
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, normal_range_male, normal_range_female, clinical_significance, interpretation_guide, lifestyle_factors, related_conditions) VALUES

('Plasma Viscosity', 'PV', 'Haematology', 'Plasma viscosity is an inflammation marker that reflects how thick the plasma portion of blood is. PV measures resistance to flow of plasma and rises with increased plasma proteins seen in inflammation and some blood disorders.', 'mPa·s', 'Lab-specific', 'Lab-specific', 'Used as a non-specific marker of inflammation and paraproteinaemia, often alongside ESR and CRP.',
'{"high": "Raised PV indicates inflammation or increased proteins, seen with infections, autoimmune diseases and paraproteinaemias.", "low": "Low PV is uncommon and usually not clinically significant.", "urgent": "PV itself is not an emergency test, but symptoms such as fever, weight loss, night sweats or severe pain need prompt assessment.", "improvement": "PV falls as the underlying inflammatory or haematological condition is treated and controlled."}'::jsonb,
ARRAY['Managing chronic infections', 'Treating autoimmune conditions'], ARRAY['Rheumatoid arthritis', 'Multiple myeloma', 'Chronic infections', 'Vasculitis']),

('Procalcitonin', 'PCT', 'Inflammation', 'Procalcitonin is an inflammation marker used mainly to help assess serious bacterial infections and sepsis. PCT is a precursor of calcitonin that rises in response to systemic bacterial infections but less so in viral infections.', 'ng/mL', '<0.1 ng/mL', '<0.1 ng/mL', 'Helps differentiate bacterial from viral infection and guides antibiotic decisions in critical care.',
'{"high": "High PCT is associated with significant bacterial infection, sepsis and sometimes severe localised infections.", "low": "Low PCT makes severe bacterial sepsis less likely, though clinical judgement is always crucial.", "urgent": "Suspected sepsis (fever, fast breathing, confusion, low blood pressure) is a medical emergency.", "improvement": "Prompt antibiotics, source control and intensive supportive care reduce PCT as infection resolves."}'::jsonb,
ARRAY['Infection prevention', 'Hygiene measures'], ARRAY['Sepsis', 'Bacterial pneumonia', 'Meningitis', 'Peritonitis']),

('Complement C3', 'C3', 'Immunology', 'C3 is a major component of the complement system involved in immunity and inflammation. C3 helps opsonise pathogens and is consumed during activation of the complement cascade.', 'g/L', '0.9–1.8 g/L', '0.9–1.8 g/L', 'Used to track autoimmune disease activity, particularly lupus nephritis and immune complex conditions.',
'{"high": "High C3 often reflects acute-phase responses or metabolic syndrome but is less commonly interpreted than low levels.", "low": "Low C3 can be seen in active immune complex diseases such as lupus nephritis and some infections.", "urgent": "Signs of kidney involvement (swelling, blood in urine, high blood pressure) or systemic autoimmune flares require urgent evaluation.", "improvement": "Rheumatology and nephrology teams use C3 with C4 and other markers to track autoimmune disease activity and guide immunosuppressive treatment."}'::jsonb,
ARRAY['Managing autoimmune conditions', 'Regular monitoring'], ARRAY['Systemic lupus erythematosus', 'Glomerulonephritis', 'Immune complex disease']),

('Complement C4', 'C4', 'Immunology', 'C4 is another complement component often measured with C3 to assess autoimmune and immune complex conditions. C4 participates in the classical complement pathway and is consumed in immune complex activation.', 'g/L', '0.15–0.50 g/L', '0.15–0.50 g/L', 'Used alongside C3 to monitor autoimmune disease activity, especially lupus and vasculitis.',
'{"high": "High C4 usually reflects an acute-phase reaction but has less specific clinical significance.", "low": "Low C4 is typical of active immune complex diseases like lupus and some types of vasculitis and glomerulonephritis.", "urgent": "Acute lupus flares with organ involvement (kidney, brain, lungs) are emergencies and need urgent specialist care.", "improvement": "C4 trends help rheumatologists tailor immunosuppressive therapy; treating the underlying disease usually normalises levels."}'::jsonb,
ARRAY['Managing autoimmune conditions', 'Regular monitoring'], ARRAY['Systemic lupus erythematosus', 'Vasculitis', 'Hereditary angioedema']),

('Microalbumin', 'MALB', 'Kidney Function', 'Urine microalbumin detects small amounts of albumin leakage from the kidneys and is an early marker of kidney damage. It measures low levels of albumin in urine not picked up by standard dipsticks, especially important in diabetes and hypertension.', 'mg/L', 'Lab-specific', 'Lab-specific', 'Key screening marker for early diabetic and hypertensive nephropathy.',
'{"high": "Raised microalbumin indicates early kidney damage (microalbuminuria), commonly from diabetes or high blood pressure.", "low": "Normal results suggest no significant early kidney damage at the time of testing.", "urgent": "Symptoms of advanced kidney disease (swelling, breathlessness, very little urine) need urgent care.", "improvement": "Tight control of blood sugar and blood pressure, use of ACE inhibitors or ARBs, and lifestyle changes can reduce albumin leakage and protect kidney function."}'::jsonb,
ARRAY['Blood pressure control', 'Blood sugar management', 'Low-salt diet', 'Regular exercise'], ARRAY['Diabetic nephropathy', 'Hypertensive kidney disease', 'Cardiovascular disease']),

('Albumin/Creatinine Ratio', 'ACR', 'Kidney Function', 'ACR adjusts urine albumin for concentration using creatinine and is the preferred screening test for kidney damage in diabetes. ACR expresses albumin excretion relative to creatinine, improving accuracy from spot urine samples.', 'mg/mmol', '<3 mg/mmol normal', '<3 mg/mmol normal', 'Preferred screening test for diabetic nephropathy and cardiovascular risk stratification.',
'{"high": "High ACR indicates kidney damage and higher cardiovascular risk, particularly in diabetes and hypertension.", "low": "Normal ACR suggests no significant albumin leak at that time.", "urgent": "Shortness of breath, severe swelling or very little urine require emergency evaluation.", "improvement": "Optimising blood pressure, blood sugar, weight, and using kidney-protective medications can lower ACR and slow progression of kidney disease."}'::jsonb,
ARRAY['Blood pressure control', 'Blood sugar management', 'Weight management', 'Reducing salt intake'], ARRAY['Diabetic nephropathy', 'Chronic kidney disease', 'Cardiovascular disease']),

('Serum Amylase', 'AMY', 'Digestive Health', 'Amylase is a digestive enzyme mainly from the pancreas and salivary glands used to assess pancreatic disorders. Blood amylase rises in acute pancreatitis and some other conditions.', 'IU/L', 'Lab-specific', 'Lab-specific', 'Primary marker for acute pancreatitis alongside lipase.',
'{"high": "High amylase occurs in acute pancreatitis, gallstones, bowel obstruction and salivary gland disease.", "low": "Low amylase rarely has clinical significance, though it may occur in chronic pancreatic damage.", "urgent": "Sudden severe upper abdominal pain, vomiting and fever need urgent hospital assessment.", "improvement": "Treatment targets pancreatitis or other underlying causes with hospital care, pain control, fluid support and sometimes procedures."}'::jsonb,
ARRAY['Limiting alcohol intake', 'Healthy diet', 'Avoiding very high-fat meals'], ARRAY['Acute pancreatitis', 'Chronic pancreatitis', 'Gallstones', 'Bowel obstruction']),

('Serum Lipase', 'LPS', 'Digestive Health', 'Lipase is a pancreatic enzyme now often preferred to amylase for diagnosing pancreatitis. Blood lipase rises in acute pancreatic inflammation.', 'IU/L', 'Lab-specific', 'Lab-specific', 'More specific than amylase for pancreatic disease; remains elevated longer after onset.',
'{"high": "Raised lipase is most commonly seen in acute and chronic pancreatitis, and may also be elevated in certain bowel and kidney disorders.", "low": "Low values are usually not clinically important.", "urgent": "Acute abdominal pain and vomiting require urgent assessment.", "improvement": "Treatment is directed at pancreatitis and related conditions, managed in hospital."}'::jsonb,
ARRAY['Limiting alcohol intake', 'Healthy diet'], ARRAY['Acute pancreatitis', 'Chronic pancreatitis', 'Gallstones']),

('Pancreatic Elastase', 'PE1', 'Digestive Health', 'Pancreatic elastase in stool is used to assess pancreatic exocrine function. It is an enzyme produced by the pancreas that remains relatively stable as it passes through the gut, so low levels in stool suggest reduced enzyme output.', 'µg/g stool', '>200 µg/g normal', '>200 µg/g normal', 'Gold standard non-invasive test for pancreatic exocrine insufficiency.',
'{"high": "Very high values are usually not clinically significant.", "low": "Low levels indicate pancreatic exocrine insufficiency, seen in chronic pancreatitis, cystic fibrosis and some other pancreatic diseases.", "urgent": "Severe weight loss, diarrhoea and malnutrition symptoms should be assessed promptly.", "improvement": "Treatment may include pancreatic enzyme replacement therapy, nutritional support and managing underlying pancreatic disease."}'::jsonb,
ARRAY['Balanced nutrition', 'Avoiding alcohol excess'], ARRAY['Chronic pancreatitis', 'Cystic fibrosis', 'Pancreatic cancer', 'Exocrine insufficiency']),

('Helicobacter pylori Antibodies', 'HPAB', 'Digestive Health', 'H. pylori antibodies indicate exposure to the stomach bacterium Helicobacter pylori. It detects IgG antibodies associated with past or current infection that can cause ulcers and gastritis.', 'Qualitative', 'Negative', 'Negative', 'Screening test for H. pylori exposure; positive results usually require confirmatory testing.',
'{"high": "Positive antibodies indicate past exposure; further tests (stool antigen, breath test) are usually needed to confirm active infection.", "low": "Negative results make active infection less likely but are not perfect.", "urgent": "Severe abdominal pain, vomiting blood or black stools need urgent assessment.", "improvement": "If active infection is confirmed, eradication therapy with antibiotics and acid-suppressing medicine is used."}'::jsonb,
ARRAY['Good hygiene', 'Avoiding contaminated food and water'], ARRAY['Peptic ulcer disease', 'Gastritis', 'Gastric cancer risk', 'MALT lymphoma']),

('Tissue Transglutaminase IgA', 'TTGA', 'Immunology', 'tTG-IgA antibodies are the main screening test for coeliac disease. These antibodies target tissue transglutaminase, an enzyme involved in gluten-related immune responses in coeliac disease.', 'U/mL', 'Lab-specific', 'Lab-specific', 'First-line serological screening for coeliac disease; must be tested while on a gluten-containing diet.',
'{"high": "Raised tTG-IgA strongly suggests coeliac disease and usually prompts further testing, often including endoscopy and biopsy.", "low": "Negative results make coeliac disease less likely, especially if total IgA is normal and gluten is present in the diet.", "urgent": "Severe weight loss, anaemia, dehydration or persistent diarrhoea need prompt review.", "improvement": "Definitive management is a strict lifelong gluten-free diet under dietetic and specialist guidance."}'::jsonb,
ARRAY['Gluten-free diet (if diagnosed)', 'Regular dietary review'], ARRAY['Coeliac disease', 'Dermatitis herpetiformis', 'Iron deficiency anaemia']),

('Anti-Endomysial Antibodies', 'EMA', 'Immunology', 'EMA testing is another highly specific coeliac disease antibody test. EMA detects IgA antibodies against endomysium that closely align with tTG antibodies in coeliac disease.', 'Qualitative', 'Negative', 'Negative', 'Highly specific confirmatory test for coeliac disease alongside tTG-IgA.',
'{"high": "Positive EMA strongly supports a diagnosis of coeliac disease.", "low": "Negative EMA reduces the likelihood of coeliac disease, especially with negative tTG-IgA.", "urgent": "Severe malabsorption symptoms should be addressed urgently.", "improvement": "A gluten-free diet, guided by specialists, is the main treatment once diagnosis is confirmed."}'::jsonb,
ARRAY['Gluten-free diet (if diagnosed)', 'Regular dietetic review'], ARRAY['Coeliac disease', 'Dermatitis herpetiformis']),

('Serum Lactate', 'LAC', 'Metabolic', 'Lactate is a product of anaerobic metabolism used to assess tissue oxygenation and sepsis severity. Lactate accumulates when tissues are not receiving enough oxygen or when metabolism is altered.', 'mmol/L', '0.5–2.0 mmol/L', '0.5–2.0 mmol/L', 'Critical marker in emergency and intensive care for tissue hypoperfusion and sepsis severity.',
'{"high": "High lactate suggests lactic acidosis, seen in sepsis, shock, severe hypoxia, some metabolic disorders and certain medications or toxins.", "low": "Low lactate is generally normal and not problematic.", "urgent": "Raised lactate in a sick person indicates possible life-threatening illness and needs emergency care.", "improvement": "Treating the underlying cause (improving oxygen delivery, fluids, antibiotics) is essential; lactate falls as perfusion and oxygenation improve."}'::jsonb,
ARRAY['Maintaining hydration', 'Avoiding excessive exertion when unwell'], ARRAY['Sepsis', 'Shock', 'Lactic acidosis', 'Tissue hypoxia']),

('Carboxyhaemoglobin', 'COHB', 'Haematology', 'Carboxyhaemoglobin measures the amount of haemoglobin bound to carbon monoxide. It forms when carbon monoxide binds to haemoglobin, reducing oxygen-carrying capacity.', '%', '<2% non-smokers', '<2% non-smokers', 'Used to diagnose carbon monoxide poisoning and assess smoking-related exposure.',
'{"high": "High levels suggest carbon-monoxide exposure (e.g. faulty heaters, fires) or heavy smoking.", "low": "Very low values are normal in non-smokers.", "urgent": "Headache, dizziness, confusion or collapse in an environment with possible CO exposure is an emergency.", "improvement": "Immediate removal from exposure and oxygen therapy, sometimes in a hyperbaric chamber; preventing future exposure is crucial."}'::jsonb,
ARRAY['Smoking cessation', 'Carbon monoxide detector use', 'Proper ventilation of gas appliances'], ARRAY['Carbon monoxide poisoning', 'Smoking-related disease']),

('Methemoglobin', 'METHB', 'Haematology', 'Methemoglobin is a form of haemoglobin that cannot carry oxygen effectively. It occurs when iron in haemoglobin is oxidised to the ferric state, reducing oxygen delivery.', '%', '<1%', '<1%', 'Used to diagnose methemoglobinaemia from drugs, chemicals or inherited enzyme deficiencies.',
'{"high": "High levels can result from certain drugs, chemicals or inherited enzyme deficiencies, leading to cyanosis and hypoxia.", "low": "Very low percentages are normal in healthy people.", "urgent": "Blue lips or skin, breathlessness, confusion or chest pain with suspected methemoglobinaemia require urgent care.", "improvement": "Treatment may include oxygen and antidotes such as methylene blue in hospital."}'::jsonb,
ARRAY['Avoiding causative drugs and chemicals'], ARRAY['Methemoglobinaemia', 'Drug-induced oxidative stress', 'Congenital enzyme deficiency']),

('Erythropoietin', 'EPO', 'Haematology', 'EPO is a hormone that stimulates red blood cell production. Produced mainly by the kidneys in response to low oxygen, EPO signals the bone marrow to make more red blood cells.', 'IU/L', 'Lab-specific', 'Lab-specific', 'Used to differentiate causes of anaemia and polycythaemia and to guide treatment in chronic kidney disease.',
'{"high": "High EPO can be seen with chronic hypoxia (lung disease, high altitude), some tumours, or as a response to anaemia.", "low": "Low EPO occurs in kidney failure and contributes to anaemia of chronic kidney disease.", "urgent": "Severe anaemia or symptoms of underlying lung or heart disease need urgent evaluation.", "improvement": "Kidney-related anaemia may be treated with EPO-stimulating agents and iron therapy; high EPO from hypoxia or tumours needs targeted management."}'::jsonb,
ARRAY['Managing chronic conditions', 'Iron supplementation when indicated'], ARRAY['Chronic kidney disease', 'Polycythaemia vera', 'Secondary polycythaemia', 'Anaemia of chronic disease']),

('Reticulocyte Count', 'RETIC', 'Haematology', 'Reticulocytes are young red blood cells; their count shows how actively the bone marrow is producing RBCs. It measures the proportion or absolute number of immature red cells in blood.', '%', '0.5–2.5%', '0.5–2.5%', 'Helps differentiate between causes of anaemia: production failure versus increased destruction or blood loss.',
'{"high": "High reticulocytes indicate increased production after blood loss, haemolysis or treatment of deficiency.", "low": "Low reticulocytes in anaemia suggest reduced marrow production from deficiencies, marrow disease or chronic illness.", "urgent": "Severe or rapidly worsening anaemia requires urgent assessment.", "improvement": "Treating iron, B12 or folate deficiency or underlying marrow disease usually normalises reticulocyte responses."}'::jsonb,
ARRAY['Adequate iron, B12 and folate intake', 'Managing chronic conditions'], ARRAY['Iron deficiency anaemia', 'Haemolytic anaemia', 'Aplastic anaemia', 'Bone marrow disorders']),

('Haptoglobin', 'HAPT', 'Haematology', 'Haptoglobin is a protein that binds free haemoglobin; low levels can indicate haemolysis. It binds haemoglobin released from red cells, allowing safe clearance.', 'g/L', '0.3–2.0 g/L', '0.3–2.0 g/L', 'Key marker for detecting intravascular haemolysis alongside LDH and bilirubin.',
'{"high": "High levels may reflect inflammation as it behaves like an acute-phase protein.", "low": "Low levels suggest increased red cell breakdown (haemolysis) or severe liver disease.", "urgent": "Signs of haemolysis (jaundice, dark urine, anaemia) need urgent evaluation.", "improvement": "Treating the cause of haemolysis or liver disease is central; haematology input is often needed."}'::jsonb,
ARRAY['Managing underlying conditions'], ARRAY['Haemolytic anaemia', 'Autoimmune haemolysis', 'Liver disease', 'Sickle cell disease']),

('Serum Tryptase', 'TRYP', 'Immunology', 'Tryptase is an enzyme released from mast cells and is used in evaluating anaphylaxis and mast cell disorders. Tryptase is stored in mast cells and released during allergic reactions and in mastocytosis.', 'µg/L', 'Lab-specific', 'Lab-specific', 'Used to confirm anaphylaxis retrospectively and diagnose systemic mastocytosis.',
'{"high": "Raised baseline tryptase suggests systemic mastocytosis or other mast cell disorders; transient elevation supports a diagnosis of anaphylaxis.", "low": "Normal levels are expected outside allergic reactions; a transient rise after anaphylaxis may fall quickly.", "urgent": "Signs of anaphylaxis (breathing difficulty, swelling, collapse) require immediate emergency treatment.", "improvement": "Allergy and immunology specialists manage mast cell disorders with avoidance strategies, antihistamines and other targeted treatments."}'::jsonb,
ARRAY['Allergen avoidance', 'Carrying emergency adrenaline if prescribed'], ARRAY['Anaphylaxis', 'Systemic mastocytosis', 'Mast cell activation syndrome']),

('Red Cell Folate', 'RCFOL', 'Vitamins & Minerals', 'Red cell folate reflects longer-term folate status than serum folate. It measures folate within red blood cells and is less affected by short-term dietary changes than serum folate.', 'nmol/L', 'Lab-specific', 'Lab-specific', 'Preferred measure of tissue folate stores; important in investigating macrocytic anaemia and pregnancy health.',
'{"high": "High values usually reflect supplementation; very high folate may mask B12 deficiency.", "low": "Low levels indicate chronic folate deficiency, which can cause macrocytic anaemia and, in pregnancy, increase neural tube defect risk.", "urgent": "Severe anaemia or neurological symptoms need urgent assessment.", "improvement": "Dietary folate (leafy greens, legumes, fortified foods) and folic acid supplements under medical guidance can correct deficiency."}'::jsonb,
ARRAY['Eating leafy green vegetables', 'Folic acid supplementation in pregnancy', 'Balanced diet'], ARRAY['Macrocytic anaemia', 'Neural tube defects', 'Folate deficiency', 'Malabsorption']);
