
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, normal_range_male, normal_range_female, clinical_significance, interpretation_guide, lifestyle_factors, related_conditions) VALUES

('Total IgE', 'IGE', 'Immunology', 'Total IgE indicates overall levels of allergy-related antibodies. IgE antibodies are involved in allergic reactions and defence against parasites. Measuring total IgE helps gauge atopic tendency but is non-specific.', 'IU/mL', 'Lab-specific', 'Lab-specific', 'Non-specific marker of atopic tendency; used alongside specific IgE and clinical history.',
'{"high": "Raised IgE can occur with eczema, asthma, hay fever, parasitic infections and some rare immunological conditions.", "low": "Normal or low IgE does not exclude allergy, as specific IgE to individual allergens may still be present.", "urgent": "Acute allergic reactions (breathing difficulty, swelling, collapse) are emergencies regardless of IgE level.", "improvement": "Treatment focuses on controlling allergic diseases with avoidance, antihistamines, inhalers or immunotherapy when appropriate."}'::jsonb,
ARRAY['Allergen avoidance', 'Managing eczema and asthma triggers'], ARRAY['Eczema', 'Asthma', 'Hay fever', 'Parasitic infections', 'Allergic bronchopulmonary aspergillosis']),

('Specific IgE', 'SIGE', 'Immunology', 'Allergen-specific IgE tests identify sensitisation to particular allergens such as pollen or foods. These tests measure IgE antibodies to defined allergens, helping identify triggers for allergic symptoms.', 'kU/L', 'Negative (<0.35)', 'Negative (<0.35)', 'Identifies sensitisation to specific allergens to guide avoidance and treatment strategies.',
'{"high": "Positive results indicate sensitisation and, together with symptoms, support a diagnosis of allergy.", "low": "Negative specific IgE suggests no sensitisation to that allergen, but does not completely rule out non-IgE-mediated reactions.", "urgent": "Suspected anaphylaxis to foods, insect stings or drugs needs urgent hospital care regardless of test status.", "improvement": "Allergy specialists advise on avoidance, emergency plans (e.g. adrenaline auto-injectors) and potential desensitisation therapies."}'::jsonb,
ARRAY['Allergen avoidance', 'Carrying emergency adrenaline if prescribed', 'Environmental controls'], ARRAY['Food allergy', 'Insect sting allergy', 'Drug allergy', 'Allergic rhinitis', 'Anaphylaxis']),

('1,25-Dihydroxyvitamin D', 'VITD125', 'Vitamins & Minerals', '1,25-dihydroxyvitamin D is the active hormone form of vitamin D involved in calcium regulation. It is produced from 25-OH vitamin D in the kidneys under control of PTH and regulates calcium absorption and bone metabolism.', 'pmol/L', 'Lab-specific', 'Lab-specific', 'Active form of vitamin D; used to investigate calcium disorders and kidney-related bone disease.',
'{"high": "High levels can be seen in hyperparathyroidism, some granulomatous diseases and vitamin D intoxication.", "low": "Low levels may occur in kidney disease and some forms of vitamin D-related rickets.", "urgent": "Symptoms of high calcium (thirst, confusion, abdominal pain) or severe bone pain require urgent review.", "improvement": "Treatment involves addressing underlying kidney, parathyroid or granulomatous disease and adjusting vitamin D and calcium intake."}'::jsonb,
ARRAY['Sun exposure', 'Dietary vitamin D', 'Managing kidney health'], ARRAY['Chronic kidney disease', 'Hyperparathyroidism', 'Sarcoidosis', 'Rickets']),

('Parathyroid Hormone', 'PTH', 'Hormones', 'PTH controls calcium and phosphate balance by acting on bone, kidney and vitamin D metabolism. PTH is secreted by parathyroid glands when calcium falls, raising blood calcium and lowering phosphate.', 'pmol/L', 'Lab-specific', 'Lab-specific', 'Key regulator of calcium; interpreted alongside calcium, phosphate and vitamin D levels.',
'{"high": "High PTH may indicate primary hyperparathyroidism (often with high calcium) or secondary hyperparathyroidism due to low vitamin D or kidney disease.", "low": "Low PTH with low calcium suggests hypoparathyroidism; low PTH with high calcium suggests non-PTH-mediated hypercalcaemia (e.g. malignancy).", "urgent": "Severe calcium imbalance symptoms (tetany, seizures, arrhythmias, confusion) are emergencies.", "improvement": "Treatment may involve surgery for primary hyperparathyroidism, vitamin D and calcium repletion, and management of chronic kidney disease."}'::jsonb,
ARRAY['Adequate calcium and vitamin D intake', 'Managing kidney health'], ARRAY['Primary hyperparathyroidism', 'Secondary hyperparathyroidism', 'Hypoparathyroidism', 'Osteoporosis']),

('Bone-Specific Alkaline Phosphatase', 'BALP', 'Bone Health', 'Bone ALP reflects bone formation and turnover. It is the fraction of ALP produced by osteoblasts during bone formation.', 'µg/L', 'Lab-specific', 'Lab-specific', 'Specific marker of osteoblast activity and bone formation rate.',
'{"high": "Raised bone ALP suggests increased bone turnover as in Paget''s disease, healing fractures, hyperparathyroidism or bone metastases.", "low": "Low levels are less common but may be seen in some rare bone and metabolic disorders.", "urgent": "Severe bone pain, deformity or fractures require timely assessment.", "improvement": "Management includes treating underlying bone disease (e.g. bisphosphonates for Paget''s, cancer therapies for metastases)."}'::jsonb,
ARRAY['Weight-bearing exercise', 'Adequate calcium and vitamin D'], ARRAY['Paget''s disease', 'Osteoporosis', 'Bone metastases', 'Hyperparathyroidism']),

('CTX', 'CTX', 'Bone Health', 'CTX is a bone resorption marker used to assess bone turnover. It measures fragments released when bone collagen is broken down.', 'ng/mL', 'Lab-specific (age/sex dependent)', 'Lab-specific (age/sex dependent)', 'Used to monitor anti-resorptive therapy and assess bone turnover in osteoporosis.',
'{"high": "High CTX indicates increased bone breakdown, seen in osteoporosis, hyperparathyroidism and some cancers.", "low": "Low CTX suggests low bone resorption, which may be appropriate during anti-resorptive therapy.", "urgent": "Sudden fractures or severe back pain should prompt urgent assessment.", "improvement": "Treatment usually includes osteoporosis therapy (e.g. bisphosphonates), optimising calcium and vitamin D and addressing endocrine causes."}'::jsonb,
ARRAY['Weight-bearing exercise', 'Adequate calcium and vitamin D', 'Avoiding smoking and excess alcohol'], ARRAY['Osteoporosis', 'Hyperparathyroidism', 'Bone metastases']),

('Cortisol (PM)', 'CORTPM', 'Hormones', 'PM cortisol helps assess loss of normal daily cortisol variation. Cortisol should be lower later in the day; a flattened or reversed pattern can suggest adrenal or pituitary disorders.', 'nmol/L', 'Lower than morning values', 'Lower than morning values', 'Used alongside morning cortisol and dynamic tests to evaluate Cushing''s syndrome and adrenal disorders.',
'{"high": "High late-day cortisol may suggest Cushing''s syndrome or chronic stress, especially when confirmed by suppression tests.", "low": "Low evening cortisol can be normal; results must be compared to appropriate reference ranges.", "urgent": "Suspected adrenal crisis or severe Cushing''s symptoms (muscle weakness, infections, very high blood pressure) need urgent evaluation.", "improvement": "Endocrinologists use dynamic tests and imaging to confirm diagnoses and guide surgery or medical therapy."}'::jsonb,
ARRAY['Stress management', 'Regular sleep patterns', 'Balanced exercise'], ARRAY['Cushing''s syndrome', 'Adrenal insufficiency', 'Chronic stress']),

('24-Hour Urinary Free Cortisol', 'UFC24', 'Hormones', 'Urinary free cortisol over 24 hours is a key screening test for Cushing''s syndrome. It measures cortisol excreted in urine, reflecting overall daily production.', 'µmol/24h', 'Lab-specific', 'Lab-specific', 'First-line screening test for Cushing''s syndrome alongside late-night salivary cortisol.',
'{"high": "High levels suggest cortisol overproduction as in Cushing''s syndrome or severe stress.", "low": "Low values may occur in adrenal insufficiency or with some medications.", "urgent": "Severe Cushingoid features or adrenal crisis signs are emergencies.", "improvement": "Further endocrine evaluation and imaging determine treatment such as surgery or medical cortisol-lowering therapy."}'::jsonb,
ARRAY['Stress management', 'Regular medical follow-up'], ARRAY['Cushing''s syndrome', 'Adrenal insufficiency', 'Pituitary adenoma']),

('Beta-2 Transferrin', 'B2TRF', 'Specialist', 'Beta-2 transferrin is a protein used to detect cerebrospinal fluid (CSF) leakage. It is largely specific to CSF; its presence in nasal or ear fluid suggests CSF leak.', 'Qualitative', 'Negative', 'Negative', 'Highly specific marker for CSF; used to confirm suspected CSF rhinorrhoea or otorrhoea.',
'{"high": "Positive results indicate CSF in the tested fluid, suggesting a skull-base defect or post-traumatic leak.", "low": "Negative results make CSF leak less likely.", "urgent": "Clear fluid from nose or ears after head injury, or signs of meningitis, require emergency assessment.", "improvement": "Specialist ENT or neurosurgical repair may be required to close the leak and prevent infection."}'::jsonb,
ARRAY['Avoiding straining after skull-base surgery'], ARRAY['CSF leak', 'Skull-base fracture', 'Post-surgical complication', 'Meningitis risk']),

('Aldosterone', 'ALDO', 'Hormones', 'Aldosterone is a hormone that helps regulate sodium, potassium and blood pressure. Produced by the adrenal cortex, aldosterone promotes sodium retention and potassium excretion.', 'pmol/L', 'Lab-specific (posture dependent)', 'Lab-specific (posture dependent)', 'Key hormone in the renin-angiotensin-aldosterone system; used to investigate secondary hypertension.',
'{"high": "High aldosterone with low renin suggests primary aldosteronism; high levels can cause hypertension and low potassium.", "low": "Low levels can occur in Addison''s disease, some drugs and hypoaldosteronism.", "urgent": "Severe high blood pressure, muscle weakness or heart rhythm problems with low potassium require urgent review.", "improvement": "Management includes confirmatory testing, imaging and, in some cases, surgery or mineralocorticoid-receptor blockers."}'::jsonb,
ARRAY['Low-salt diet', 'Blood pressure monitoring', 'Potassium-rich foods'], ARRAY['Primary aldosteronism', 'Addison''s disease', 'Resistant hypertension', 'Hypokalaemia']),

('Plasma Renin', 'REN', 'Hormones', 'Renin is an enzyme from the kidney that triggers the renin-angiotensin-aldosterone system. Renin converts angiotensinogen to angiotensin I, leading to aldosterone release and blood pressure regulation.', 'mU/L', 'Lab-specific (posture dependent)', 'Lab-specific (posture dependent)', 'Interpreted with aldosterone to classify hypertension and screen for primary aldosteronism.',
'{"high": "High renin can result from renal artery stenosis, diuretics, low sodium intake or some forms of hypertension.", "low": "Low renin with high aldosterone suggests primary aldosteronism; low renin with low aldosterone can occur in some kidney or genetic conditions.", "urgent": "Severe or resistant hypertension with symptoms like chest pain or neurological signs needs urgent care.", "improvement": "Management may include imaging of renal arteries, adjusting medicines and targeted treatment of secondary hypertension."}'::jsonb,
ARRAY['Salt intake management', 'Blood pressure monitoring'], ARRAY['Primary aldosteronism', 'Renal artery stenosis', 'Secondary hypertension']),

('Aldosterone/Renin Ratio', 'ARR', 'Hormones', 'ARR screens for primary aldosteronism in hypertension. It is the ratio of aldosterone concentration to renin, highlighting aldosterone excess relative to renin.', 'Ratio', 'Lab-specific', 'Lab-specific', 'First-line screening test for primary aldosteronism in patients with resistant hypertension.',
'{"high": "High ARR with high aldosterone and suppressed renin points towards primary aldosteronism.", "low": "Low ARR may indicate renin-mediated hypertension or other causes.", "urgent": "Symptomatic or very high blood pressure requires urgent assessment regardless of ARR.", "improvement": "Endocrinologists confirm the diagnosis with suppression tests and imaging and may recommend surgery or medical therapy."}'::jsonb,
ARRAY['Blood pressure monitoring', 'Low-salt diet'], ARRAY['Primary aldosteronism', 'Conn''s syndrome', 'Resistant hypertension']),

('Serum Ammonia', 'NH3', 'Liver Function', 'Ammonia is a nitrogenous waste product; high levels can affect brain function. It is produced from protein metabolism and detoxified by the liver into urea.', 'µmol/L', 'Lab-specific', 'Lab-specific', 'Used to assess hepatic encephalopathy and inherited metabolic disorders.',
'{"high": "Raised ammonia occurs in liver failure, some genetic metabolic disorders and certain drug or toxin exposures and can cause encephalopathy.", "low": "Low ammonia is usually not a concern.", "urgent": "Confusion, drowsiness, personality change or coma in liver disease are emergencies.", "improvement": "Treatment includes managing liver failure, reducing protein load, lactulose and other therapies in hospital."}'::jsonb,
ARRAY['Limiting alcohol', 'Balanced protein intake in liver disease'], ARRAY['Hepatic encephalopathy', 'Liver failure', 'Urea cycle disorders', 'Cirrhosis']),

('Ceruloplasmin', 'CP', 'Liver Function', 'Ceruloplasmin is a copper-carrying protein used in the assessment of copper metabolism disorders. It transports copper and has oxidase activity; levels reflect copper status in some conditions.', 'g/L', '0.20–0.60 g/L', '0.20–0.60 g/L', 'Key marker for Wilson''s disease diagnosis alongside serum and urinary copper.',
'{"high": "High levels can be seen in inflammation, pregnancy and oestrogen therapy.", "low": "Low levels suggest Wilson''s disease, severe copper deficiency or protein-loss states.", "urgent": "Neurological and liver symptoms in suspected Wilson''s disease need urgent specialist assessment.", "improvement": "Further copper studies and genetic tests guide treatment such as chelation or zinc therapy in Wilson''s disease."}'::jsonb,
ARRAY['Balanced copper intake', 'Avoiding excess copper in Wilson''s disease'], ARRAY['Wilson''s disease', 'Copper deficiency', 'Menkes disease']),

('Alpha-1 Antitrypsin', 'A1AT', 'Liver Function', 'A1AT protects tissues from enzyme damage and deficiency can cause lung and liver disease. It is a protease inhibitor produced by the liver, protecting lungs from neutrophil elastase.', 'g/L', '1.0–2.0 g/L', '1.0–2.0 g/L', 'Screening test for A1AT deficiency, an important genetic cause of early emphysema and liver disease.',
'{"high": "A1AT can rise as an acute-phase reactant in inflammation.", "low": "Low levels indicate A1AT deficiency, which increases risk of early emphysema and liver disease.", "urgent": "Breathlessness, chronic cough or jaundice in known deficiency should prompt timely review.", "improvement": "Management includes smoking avoidance, vaccinations, lung specialist follow-up and, in some regions, augmentation therapy or transplant in advanced disease."}'::jsonb,
ARRAY['Smoking cessation', 'Vaccinations', 'Avoiding lung irritants'], ARRAY['Alpha-1 antitrypsin deficiency', 'Emphysema', 'Liver cirrhosis', 'COPD']),

('Anti-Mitochondrial Antibodies', 'AMA', 'Immunology', 'AMA are autoantibodies strongly associated with primary biliary cholangitis (PBC). They target mitochondrial antigens in bile-duct cells.', 'Titre', 'Negative', 'Negative', 'Highly specific marker for primary biliary cholangitis; positive in over 90% of PBC cases.',
'{"high": "Positive AMA, especially with cholestatic liver tests, supports a diagnosis of PBC.", "low": "Negative AMA makes PBC less likely but does not fully exclude other cholestatic diseases.", "urgent": "Severe pruritus, jaundice or signs of liver failure require urgent assessment.", "improvement": "Hepatologists use liver tests, imaging and sometimes biopsy; treatment often includes ursodeoxycholic acid and monitoring for complications."}'::jsonb,
ARRAY['Limiting alcohol', 'Regular liver monitoring'], ARRAY['Primary biliary cholangitis', 'Cholestatic liver disease']),

('Anti-Smooth Muscle Antibodies', 'ASMA', 'Immunology', 'ASMAs are autoantibodies associated with autoimmune hepatitis and some other conditions. They target smooth muscle antigens and are detected in some autoimmune liver diseases.', 'Titre', 'Negative', 'Negative', 'Used alongside other autoantibodies and liver biopsy to diagnose autoimmune hepatitis.',
'{"high": "Positive ASMA, especially with raised liver enzymes and compatible biopsy, supports autoimmune hepatitis.", "low": "Negative ASMA does not exclude autoimmune hepatitis, as other antibodies can be involved.", "urgent": "Acute hepatitis with jaundice, coagulopathy or encephalopathy requires emergency care.", "improvement": "Treatment is usually with immunosuppressive drugs such as steroids and azathioprine under specialist supervision."}'::jsonb,
ARRAY['Limiting alcohol', 'Avoiding hepatotoxic substances'], ARRAY['Autoimmune hepatitis', 'Primary sclerosing cholangitis']),

('Anti-dsDNA Antibodies', 'DSDNA', 'Immunology', 'Anti-dsDNA antibodies are highly specific for systemic lupus erythematosus (SLE). They target double-stranded DNA and are associated with lupus activity, especially kidney involvement.', 'IU/mL', 'Negative', 'Negative', 'Highly specific for SLE; titres often correlate with disease activity and lupus nephritis.',
'{"high": "High titres support SLE diagnosis and often correlate with disease flares, particularly lupus nephritis.", "low": "Negative results make SLE less likely, especially if ANA is also negative.", "urgent": "SLE flares with kidney, brain or lung involvement require urgent specialist care.", "improvement": "Rheumatologists adjust immunosuppressive treatments based on symptoms, anti-dsDNA levels and complement components."}'::jsonb,
ARRAY['Sun protection', 'Regular specialist follow-up', 'Stress management'], ARRAY['Systemic lupus erythematosus', 'Lupus nephritis', 'Autoimmune disease']),

('ANCA', 'ANCA', 'Immunology', 'ANCA help diagnose certain vasculitides such as granulomatosis with polyangiitis. ANCA target antigens in neutrophil cytoplasm, typically MPO or PR3.', 'Titre', 'Negative', 'Negative', 'Used to diagnose and monitor ANCA-associated vasculitis (GPA, MPA, EGPA).',
'{"high": "Positive ANCA supports diagnoses such as GPA or microscopic polyangiitis, especially with compatible symptoms.", "low": "Negative ANCA does not fully exclude vasculitis but makes classic ANCA-associated vasculitis less likely.", "urgent": "Blood in urine, coughing blood, breathlessness or neurological symptoms with suspected vasculitis need urgent hospital care.", "improvement": "Management involves immunosuppressive regimens under specialist care and close monitoring for organ involvement."}'::jsonb,
ARRAY['Regular specialist monitoring', 'Infection prevention during immunosuppression'], ARRAY['Granulomatosis with polyangiitis', 'Microscopic polyangiitis', 'Eosinophilic granulomatosis']),

('Serum ACE', 'SACE', 'Immunology', 'Serum ACE is sometimes used as a marker for sarcoidosis activity. ACE converts angiotensin I to II and degrades bradykinin; elevated levels can reflect granulomatous disease.', 'U/L', 'Lab-specific', 'Lab-specific', 'Non-specific marker sometimes elevated in sarcoidosis; used alongside imaging and clinical findings.',
'{"high": "Raised ACE may occur in sarcoidosis and some other conditions but is non-specific.", "low": "Low ACE is usually due to ACE-inhibitor medications or has limited clinical significance.", "urgent": "Sarcoidosis with acute breathlessness, visual changes or neurological symptoms needs urgent review.", "improvement": "Specialists interpret ACE alongside imaging and symptoms; treatment may include corticosteroids or other immunosuppressants."}'::jsonb,
ARRAY['Regular monitoring if diagnosed with sarcoidosis'], ARRAY['Sarcoidosis', 'Granulomatous disease', 'Gaucher disease']);
