
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, clinical_significance, normal_range_male, normal_range_female, interpretation_guide, lifestyle_factors, related_conditions) VALUES

('Creatine Kinase (CK)', 'CK', 'Enzymes', 'Creatine kinase is an enzyme found mainly in muscle and is used to assess muscle injury. CK helps cells store and release energy and is abundant in skeletal muscle, heart muscle and brain.', 'IU/L', 'Muscle injury and muscle disease assessment', '39-308 IU/L', '26-192 IU/L',
'{"high": {"description": "Raised CK can occur with strenuous exercise, muscle injury, injections or surgery, inflammatory muscle diseases, rhabdomyolysis, certain medicines (e.g. statins) and rare genetic muscle conditions. Very high CK can cause or reflect muscle breakdown that may damage the kidneys.", "urgentAdvice": "Seek urgent help for severe muscle pain, weakness, swelling, dark urine or reduced urine output, as these may suggest rhabdomyolysis.", "improvements": ["Rest from intense exercise", "Stop or change offending medicines under medical advice", "Treat underlying muscle disease", "Ensure good hydration"]}, "low": {"description": "Low CK is usually not clinically significant and can be seen in people with low muscle mass.", "improvements": ["No action typically needed"]}}',
ARRAY['Exercise intensity', 'Medication use', 'Hydration'],
ARRAY['Rhabdomyolysis', 'Myositis', 'Muscular dystrophy', 'Statin myopathy']),

('CK-MB', 'CKMB', 'Cardiac', 'CK-MB is a CK isoenzyme more concentrated in heart muscle and was traditionally used to assess heart damage. The heart contains a higher proportion of CK-MB than skeletal muscle.', 'µg/L', 'Heart muscle injury assessment', NULL, NULL,
'{"high": {"description": "Raised CK-MB can indicate heart muscle damage (for example, heart attack), but is now largely superseded by troponin tests because CK-MB is less specific. CK-MB can also rise in skeletal muscle disorders and trauma.", "urgentAdvice": "Chest pain, shortness of breath, sweating or jaw/arm pain are emergencies and need urgent hospital assessment.", "improvements": ["Urgent cardiac assessment if heart attack suspected", "Troponin is now the preferred marker"]}, "low": {"description": "Low or undetectable CK-MB is normal and suggests no recent significant myocardial injury.", "improvements": ["No action needed"]}}',
ARRAY['Physical activity', 'Cardiac health'],
ARRAY['Myocardial infarction', 'Myocarditis', 'Skeletal muscle trauma']),

('Troponin I', 'TROPI', 'Cardiac', 'Troponin I is a cardiac protein and the key biomarker used to detect heart muscle injury. It is part of the contractile apparatus in heart muscle cells.', 'ng/L', 'Heart muscle damage detection and cardiac risk assessment', NULL, NULL,
'{"high": {"description": "Raised troponin I indicates heart muscle injury from causes such as heart attack, myocarditis, heart failure or severe strain on the heart. Even moderate elevations can signal increased cardiovascular risk.", "urgentAdvice": "Any suspicion of heart attack (chest pain, breathlessness, collapse) is an emergency; do not rely on troponin alone without urgent medical review.", "improvements": ["Emergency procedures for heart attack if indicated", "Medications for underlying heart disease", "Management of vascular risk factors"]}, "low": {"description": "Very low or undetectable troponin I is expected in people without heart muscle damage.", "improvements": ["No action needed"]}}',
ARRAY['Cardiovascular health', 'Physical activity', 'Stress management'],
ARRAY['Myocardial infarction', 'Myocarditis', 'Heart failure', 'Pulmonary embolism']),

('Troponin T', 'TROPT', 'Cardiac', 'Troponin T is another cardiac troponin used similarly to troponin I to assess heart damage. It is a component of the troponin complex in heart muscle.', 'ng/L', 'Heart muscle damage detection and cardiac risk assessment', NULL, NULL,
'{"high": {"description": "Raised troponin T indicates heart muscle damage from heart attack or other serious cardiac conditions. It may also be modestly raised in kidney disease and chronic heart failure.", "urgentAdvice": "Acute chest pain or collapse should always be treated as an emergency.", "improvements": ["Urgent cardiac assessment, ECGs and imaging", "Long-term management focuses on reducing further heart damage", "Control cardiovascular risk factors"]}, "low": {"description": "Low or undetectable levels are normal.", "improvements": ["No action needed"]}}',
ARRAY['Cardiovascular health', 'Kidney health', 'Physical activity'],
ARRAY['Myocardial infarction', 'Heart failure', 'Kidney disease', 'Myocarditis']),

('Myoglobin', 'MYO', 'Cardiac', 'Myoglobin is an oxygen-binding protein in muscle that can rise quickly after muscle injury. It is found in heart and skeletal muscle.', 'µg/L', 'Early muscle and cardiac injury detection', NULL, NULL,
'{"high": {"description": "Raised myoglobin occurs with muscle injury, heart attack and rhabdomyolysis. Very high myoglobin can contribute to kidney damage.", "urgentAdvice": "Severe muscle pain, dark urine or chest pain are emergencies.", "improvements": ["Aggressive hydration", "Treat the cause of muscle damage", "Monitor kidney function"]}, "low": {"description": "Low myoglobin is usually not clinically important.", "improvements": ["No action needed"]}}',
ARRAY['Exercise intensity', 'Hydration', 'Cardiac health'],
ARRAY['Rhabdomyolysis', 'Myocardial infarction', 'Acute kidney injury']),

('BNP / NT-proBNP', 'BNP', 'Cardiac', 'BNP and NT-proBNP are hormones released by the heart in response to stretching and are used to assess heart failure. They help regulate blood pressure and fluid balance.', 'pg/mL', 'Heart failure assessment and cardiac stress marker', NULL, NULL,
'{"high": {"description": "Raised levels are associated with heart failure, atrial fibrillation, pulmonary hypertension and other cardiac and lung conditions.", "urgentAdvice": "Shortness of breath at rest, chest pain, swelling with breathlessness or sudden weight gain from fluid retention require urgent assessment.", "improvements": ["Lifestyle changes for heart failure management", "Medicines such as diuretics and ACE inhibitors", "Manage blood pressure and rhythm problems"]}, "low": {"description": "Low levels generally suggest the absence of significant heart failure.", "improvements": ["No action needed"]}}',
ARRAY['Cardiovascular health', 'Salt intake', 'Physical activity', 'Weight management'],
ARRAY['Heart failure', 'Atrial fibrillation', 'Pulmonary hypertension', 'Cardiomyopathy']),

('PSA (Prostate-Specific Antigen)', 'PSA', 'Cancer Screening', 'PSA is a protein made by the prostate and is used in prostate disease assessment. Levels can rise with prostate enlargement, inflammation or cancer.', 'µg/L', 'Prostate disease and prostate cancer risk assessment', NULL, NULL,
'{"high": {"description": "Raised PSA can occur with benign prostatic hyperplasia (BPH), prostatitis or prostate cancer. PSA is not cancer-specific and must be interpreted with symptoms and examination findings.", "urgentAdvice": "Difficulty passing urine, urinary retention, blood in urine or bone pain should prompt urgent review.", "improvements": ["GP may repeat the test and perform rectal examination", "Referral to urology for MRI or biopsy if needed", "Lifestyle steps support general prostate health"]}, "low": {"description": "Low PSA is expected in men without significant prostate disease.", "improvements": ["No action needed"]}}',
ARRAY['Age', 'Diet', 'Physical activity'],
ARRAY['Prostate cancer', 'Benign prostatic hyperplasia', 'Prostatitis']),

('CA-125', 'CA125', 'Cancer Screening', 'CA-125 is a tumour marker often used in the assessment of ovarian cancer risk. It can be raised in ovarian cancer and some benign conditions including endometriosis and pelvic infections.', 'U/mL', 'Ovarian cancer risk assessment and monitoring', NULL, NULL,
'{"high": {"description": "Raised CA-125 can result from ovarian cancer, other cancers, benign gynaecological conditions and even normal menstruation or pregnancy.", "urgentAdvice": "Persistent bloating, abdominal pain, early satiety or urinary urgency, especially in women over 50, should prompt urgent GP review.", "improvements": ["Repeat tests and ultrasound scans may be organised", "Referral to specialist if indicated", "Used as part of risk assessment, not a stand-alone diagnostic test"]}, "low": {"description": "Normal levels do not fully exclude ovarian cancer but make it less likely when symptoms are absent.", "improvements": ["No action needed"]}}',
ARRAY['Menstrual cycle', 'Age', 'Family history'],
ARRAY['Ovarian cancer', 'Endometriosis', 'Pelvic inflammatory disease', 'Uterine fibroids']),

('CEA (Carcinoembryonic Antigen)', 'CEA', 'Cancer Screening', 'CEA is a tumour marker mainly used to monitor colorectal and some other cancers. It is a glycoprotein produced by some tumours and, at low levels, by normal tissues.', 'µg/L', 'Colorectal and other cancer monitoring', '0-3 µg/L (non-smokers)', '0-3 µg/L (non-smokers)',
'{"high": {"description": "Raised CEA can occur in colorectal, pancreatic, lung and breast cancers and in benign conditions such as smoking, inflammation and liver disease.", "urgentAdvice": "Unintentional weight loss, rectal bleeding, change in bowel habit or abdominal pain should be assessed promptly regardless of CEA.", "improvements": ["CEA is mainly used by specialists to monitor treatment response or detect recurrence", "Imaging and clinical assessment guide management"]}, "low": {"description": "Normal CEA does not exclude cancer but is reassuring, especially in follow-up when stable over time.", "improvements": ["No action needed"]}}',
ARRAY['Smoking', 'Diet', 'Bowel health'],
ARRAY['Colorectal cancer', 'Pancreatic cancer', 'Lung cancer', 'Breast cancer']),

('CA19-9', 'CA199', 'Cancer Screening', 'CA19-9 is a tumour marker associated primarily with pancreatic and biliary cancers. It can also be raised in benign biliary and pancreatic disease.', 'U/mL', 'Pancreatic and biliary cancer monitoring', '0-37 U/mL', '0-37 U/mL',
'{"high": {"description": "High CA19-9 occurs in pancreatic, biliary and some gastric cancers and in cholangitis, gallstones and pancreatitis.", "urgentAdvice": "Jaundice, unexplained weight loss, abdominal pain or pale stools require urgent evaluation.", "improvements": ["Interpretation is by specialists alongside imaging", "CA19-9 is mainly used for monitoring, not screening"]}, "low": {"description": "Normal levels do not exclude pancreatic or biliary cancer.", "improvements": ["No action needed"]}}',
ARRAY['Diet', 'Alcohol intake'],
ARRAY['Pancreatic cancer', 'Cholangiocarcinoma', 'Pancreatitis', 'Gallstones']),

('AFP (Alpha-Fetoprotein)', 'AFP', 'Cancer Screening', 'AFP is a protein used as a tumour marker in liver cancer and some germ-cell tumours. It is produced by the fetal liver; in adults, high levels can signal certain cancers or liver conditions.', 'µg/L', 'Liver cancer and germ-cell tumour monitoring', '0-10 µg/L', '0-10 µg/L',
'{"high": {"description": "Raised AFP occurs in hepatocellular carcinoma, some testicular tumours and in active liver disease such as hepatitis.", "urgentAdvice": "Unexplained weight loss, abdominal swelling, jaundice or testicular lumps should prompt urgent review.", "improvements": ["Specialists use AFP with imaging to diagnose and monitor liver and germ-cell tumours"]}, "low": {"description": "Normal AFP is expected in healthy adults and does not exclude cancer on its own.", "improvements": ["No action needed"]}}',
ARRAY['Alcohol intake', 'Liver health', 'Hepatitis status'],
ARRAY['Hepatocellular carcinoma', 'Testicular cancer', 'Hepatitis', 'Cirrhosis']),

('Beta-hCG (Non-Pregnant)', 'BHCG', 'Cancer Screening', 'Outside pregnancy, beta-hCG can act as a tumour marker for certain cancers. It is a hormone produced by the placenta in pregnancy and, abnormally, by some tumours.', 'IU/L', 'Tumour marker for germ-cell and trophoblastic tumours', NULL, NULL,
'{"high": {"description": "Raised beta-hCG may indicate pregnancy, gestational trophoblastic disease or some germ-cell tumours.", "urgentAdvice": "Positive beta-hCG in a non-pregnant context, or any pregnancy with pain or bleeding, requires urgent evaluation.", "improvements": ["In cancer care, beta-hCG is monitored by specialists to assess treatment response", "In pregnancy, levels are interpreted with ultrasound and clinical findings"]}, "low": {"description": "This is normal in non-pregnant individuals.", "improvements": ["No action needed"]}}',
ARRAY['Reproductive health'],
ARRAY['Gestational trophoblastic disease', 'Testicular cancer', 'Ovarian germ-cell tumours']),

('IGF-1 (Insulin-Like Growth Factor-1)', 'IGF1', 'Hormones', 'IGF-1 reflects average growth hormone activity and is used to assess disorders of growth. It is mainly produced in the liver in response to growth hormone.', 'nmol/L', 'Growth hormone activity and growth disorder assessment', NULL, NULL,
'{"high": {"description": "High IGF-1 is seen in acromegaly and other conditions with excess growth hormone.", "urgentAdvice": "Symptoms such as rapid change in facial features, hand or foot size, severe headaches or visual problems should be assessed urgently.", "improvements": ["Endocrinology assessment with GH suppression tests and imaging", "Treatment may include surgery, medicines or radiotherapy"]}, "low": {"description": "Low IGF-1 can indicate growth hormone deficiency, chronic illness or malnutrition.", "improvements": ["Endocrine investigation with GH stimulation tests", "Treatment of underlying cause"]}}',
ARRAY['Nutrition', 'Sleep', 'Physical activity'],
ARRAY['Acromegaly', 'Growth hormone deficiency', 'Pituitary tumours']),

('Growth Hormone (GH)', 'GH', 'Hormones', 'Growth hormone regulates growth, metabolism and body composition. It is secreted in pulses from the pituitary and stimulates IGF-1 production.', 'µg/L', 'Growth regulation and pituitary function assessment', NULL, NULL,
'{"high": {"description": "High GH causes acromegaly in adults and gigantism in children and is usually due to a pituitary tumour.", "urgentAdvice": "Visual changes, severe headaches or rapid changes in physical features need prompt specialist evaluation.", "improvements": ["Surgery, GH-blocking drugs or radiotherapy under endocrine team care"]}, "low": {"description": "Low GH can cause poor growth in children and altered body composition and low energy in adults with deficiency.", "improvements": ["Dynamic testing and pituitary imaging", "GH replacement therapy if confirmed deficiency"]}}',
ARRAY['Sleep', 'Exercise', 'Nutrition', 'Stress'],
ARRAY['Acromegaly', 'Gigantism', 'Growth hormone deficiency', 'Pituitary tumours']),

('ACTH (Adrenocorticotropic Hormone)', 'ACTH', 'Hormones', 'ACTH is a pituitary hormone that stimulates cortisol production by the adrenal glands. It is released in a daily rhythm and in response to stress.', 'pmol/L', 'Adrenal and pituitary function assessment', NULL, NULL,
'{"high": {"description": "High ACTH with high cortisol suggests ACTH-dependent Cushing''s syndrome; high ACTH with low cortisol suggests primary adrenal failure (Addison''s disease).", "urgentAdvice": "Adrenal crisis (severe weakness, vomiting, abdominal pain, low blood pressure) is a medical emergency.", "improvements": ["Investigation and treatment of ACTH-secreting tumours for Cushing''s", "Steroid replacement for adrenal insufficiency"]}, "low": {"description": "Low ACTH with low cortisol suggests secondary adrenal insufficiency from pituitary or hypothalamic disease.", "improvements": ["Pituitary investigation and imaging", "Appropriate hormone replacement"]}}',
ARRAY['Stress', 'Sleep', 'Medication use'],
ARRAY['Cushing''s syndrome', 'Addison''s disease', 'Pituitary tumours', 'Adrenal insufficiency']),

('Beta-2 Microglobulin', 'B2M', 'Cancer Screening', 'Beta-2 microglobulin is a small protein used as a marker of certain blood cancers and kidney function. It is part of MHC class I molecules on cell surfaces.', 'mg/L', 'Blood cancer prognosis and kidney function marker', NULL, NULL,
'{"high": {"description": "High beta-2 microglobulin is seen in multiple myeloma, lymphomas and some kidney diseases and is used in prognosis and monitoring.", "urgentAdvice": "Bone pain, recurrent infections, weight loss or kidney failure symptoms require urgent assessment.", "improvements": ["Oncology and nephrology teams interpret alongside other tests", "Treatment targets the underlying cancer or kidney condition"]}, "low": {"description": "Low levels are generally not clinically important.", "improvements": ["No action needed"]}}',
ARRAY['Immune health', 'Kidney health'],
ARRAY['Multiple myeloma', 'Lymphoma', 'Chronic kidney disease', 'Amyloidosis']),

('5-HIAA (5-Hydroxyindoleacetic Acid)', '5HIAA', 'Cancer Screening', '5-HIAA is the main breakdown product of serotonin and is used to investigate some neuroendocrine tumours. It is measured in a 24-hour urine collection.', 'µmol/24h', 'Neuroendocrine tumour (carcinoid) detection', NULL, NULL,
'{"high": {"description": "High 5-HIAA suggests carcinoid syndrome from neuroendocrine tumours and can cause flushing, diarrhoea and wheezing.", "urgentAdvice": "Severe flushing, breathing difficulty or heart problems with suspected carcinoid syndrome need urgent specialist assessment.", "improvements": ["Oncologists use 5-HIAA with imaging to diagnose and monitor neuroendocrine tumours", "Treatment may involve surgery, somatostatin analogues and other therapies"]}, "low": {"description": "Normal levels make serotonin-secreting tumours less likely but do not always exclude them.", "improvements": ["No action needed"]}}',
ARRAY['Diet (serotonin-rich foods can affect results)', 'Medication use'],
ARRAY['Carcinoid syndrome', 'Neuroendocrine tumours']),

('Leptin', 'LEPTIN', 'Hormones', 'Leptin is a hormone produced by fat tissue that helps regulate appetite and body weight. It signals the brain about energy stores and normally reduces appetite when fat stores are sufficient.', 'ng/mL', 'Appetite regulation and metabolic health assessment', NULL, NULL,
'{"high": {"description": "High leptin is common in obesity and may reflect leptin resistance, where the brain does not respond properly to leptin''s appetite-regulating signal.", "improvements": ["Weight loss", "Improved insulin sensitivity", "Healthy sleep and activity patterns"]}, "low": {"description": "Very low leptin can be seen in rare genetic leptin deficiency and in extreme weight loss or undernutrition.", "urgentAdvice": "Leptin abnormalities themselves are not acute emergencies; urgency depends on associated conditions (e.g. severe eating disorders).", "improvements": ["Specialist endocrine care for rare genetic disorders", "Nutritional rehabilitation for undernutrition"]}}',
ARRAY['Body weight', 'Sleep quality', 'Physical activity', 'Diet quality'],
ARRAY['Obesity', 'Leptin resistance', 'Eating disorders', 'Congenital leptin deficiency']),

('Fructosamine', 'FRUCT', 'Diabetes', 'Fructosamine reflects average blood glucose over the previous 2-3 weeks. It measures glycated serum proteins, mainly albumin, as an alternative to HbA1c in certain situations.', 'µmol/L', 'Short-term blood glucose control assessment', NULL, NULL,
'{"high": {"description": "High fructosamine indicates higher average blood sugar and is used to monitor diabetes control when HbA1c is unreliable.", "urgentAdvice": "Symptoms of very high or very low blood sugar (thirst, confusion, drowsiness) are emergencies.", "improvements": ["Lifestyle measures (diet, activity, weight management)", "Adjustment of diabetes medicines under medical supervision"]}, "low": {"description": "Low values may reflect low protein levels or improved glucose control.", "improvements": ["Monitor protein status if persistently low"]}}',
ARRAY['Diet', 'Physical activity', 'Weight management', 'Diabetes medication'],
ARRAY['Diabetes mellitus', 'Haemoglobinopathies', 'Hypoalbuminaemia']);
