-- Generated from supabase/functions/_shared/scrape/lola-catalogue.ts.
-- Do not hand-edit: change the catalogue and regenerate.

-- 1. Turnaround: default first, then the specific rules in reverse order
--    so the first matching rule wins, as in lolaTurnaround().
update public.provider_tests set turnaround_days_text = '2 working days', turnaround_not_stated = false where provider_id = 'lola-health';
update public.provider_tests set turnaround_days_text = '2-3 working days', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Peak Insights 70';
update public.provider_tests set turnaround_days_text = '5 working days', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Sickle Cell Hemoglobin Electrophoresis';
update public.provider_tests set turnaround_days_text = '35 working days', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Sickle Cell Anemia';
update public.provider_tests set turnaround_days_text = '3-4 weeks', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'GutID%';
update public.provider_tests set turnaround_days_text = '3-4 weeks', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'TruHealth%';
update public.provider_tests set turnaround_days_text = '3-4 weeks', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'TruAge%';
update public.provider_tests set turnaround_days_text = '24-48 hours', turnaround_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Urinalysis%';

-- 2. Verified panel biomarker lists.
update public.provider_tests set biomarkers_list = '["Albumin","Ferritin","Globulin","Calcium","Adjusted Calcium","Cholesterol","HDL Cholesterol","HDL Cholesterol %","Cholesterol:HDL Ratio","LDL Cholesterol","Non-HDL Cholesterol","Triglycerides","HbA1c","Basophils","Eosinophils","Haematocrit","Haemoglobin","Lymphocytes","MCHC","Mean Corpuscular Haemoglobin (MCH)","Mean Cell Volume","Mean Platelet Volume (MPV)","Monocytes","Neutrophils","Platelets","Red Blood Cell Count","Red Cell Distribution","White Blood Cells","C-Reactive Protein (CRP)","Uric Acid","Creatinine","eGFR","Urea","Alanine Aminotransferase (ALT)","Alkaline Phosphatase","Total Bilirubin","Total Protein","Creatine Kinase (CK)","Follicle-Stimulating Hormone","Luteinising Hormone","Prolactin","Oestradiol","Total Testosterone","Free Androgen Index (FAI)","Free Testosterone","SHBG","Cortisol","Free T3","Free T4","Thyroid-Stimulating Hormone","Active (bioavailable) Vitamin B12","Magnesium","Folate (Vitamin B9)","Vitamin D (25-OH)","Gamma GT"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Vital Check 56';
update public.provider_tests set biomarkers_list = '["Albumin","Ferritin","Calcium","Adjusted Calcium","Cholesterol","HDL Cholesterol","HDL Cholesterol %","Cholesterol:HDL Ratio","LDL Cholesterol","Non-HDL Cholesterol","Triglycerides","HbA1c","High-Sensitivity CRP","Follicle-Stimulating Hormone","Luteinising Hormone","Prolactin","Progesterone","DHEA-Sulphate","Oestradiol","Total Testosterone","Free Androgen Index (FAI)","Free Testosterone","SHBG","Cortisol","Free T3","Free T4","Thyroid-Stimulating Hormone","Active (bioavailable) Vitamin B12","Magnesium","Folate (Vitamin B9)","Vitamin D (25-OH)"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Female Hormones Clarity 31';
update public.provider_tests set biomarkers_list = '["Ferritin","Total Iron-Binding Capacity","Transferrin","Transferrin Saturation","Calcium","Adjusted Calcium","Basophils","Eosinophils","Haematocrit","Haemoglobin","Lymphocytes","MCHC","Mean Corpuscular Haemoglobin (MCH)","Mean Cell Volume","Mean Platelet Volume (MPV)","Monocytes","Neutrophils","Platelets","Red Blood Cell Count","Red Cell Distribution","White Blood Cells","C-Reactive Protein (CRP)","Creatine Kinase (CK)","Follicle-Stimulating Hormone","Luteinising Hormone","Prolactin","Progesterone","Oestradiol","Total Testosterone","Free Androgen Index (FAI)","Free Testosterone","SHBG","Cortisol","Free T3","Free T4","Thyroid-Stimulating Hormone","Active (bioavailable) Vitamin B12","Magnesium","Vitamin D (25-OH)"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Female Active Boost 39';
update public.provider_tests set biomarkers_list = '["Albumin","Ferritin","Follicle-Stimulating Hormone","Luteinising Hormone","Prolactin","DHEA-Sulphate","Total Testosterone","Free Testosterone","SHBG","Cortisol","Free T3","Free T4","Thyroid-Stimulating Hormone","Magnesium"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Male Hormones Clarity 14';
update public.provider_tests set biomarkers_list = '["Albumin","Ferritin","Globulin","Calcium","Adjusted Calcium","Cholesterol","HDL Cholesterol","HDL Cholesterol %","Cholesterol:HDL Ratio","LDL Cholesterol","Non-HDL Cholesterol","Triglycerides","HbA1c","Basophils","Eosinophils","Haematocrit","Haemoglobin","Lymphocytes","MCHC","Mean Corpuscular Haemoglobin (MCH)","Mean Cell Volume","Mean Platelet Volume (MPV)","Monocytes","Neutrophils","Platelets","Red Blood Cell Count","Red Cell Distribution","White Blood Cells","C-Reactive Protein (CRP)","Uric Acid","Creatinine","eGFR","Urea","Alkaline Phosphatase","Alanine Aminotransferase (ALT)","Total Bilirubin","Total Protein","Oestradiol","Total Testosterone","Free Androgen Index (FAI)","Free Testosterone","Active (bioavailable) Vitamin B12","Magnesium","Vitamin D (25-OH)","Gamma GT"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Core Health 45';
update public.provider_tests set biomarkers_list = '["pH","Glucose (Urine)","Ketones (Urine)","Blood (Haematuria)","Urobilinogen","Nitrite","Specific Gravity","Colour","Appearance","Epithelial Cells","Casts","Crystals","Bacteria","Chromium","Copper","Mercury","White Blood Cells (Urine)","Red Blood Cells (Urine)"]'::jsonb, biomarkers_not_stated = false where provider_id = 'lola-health' and btrim(test_name) ilike 'Urinalysis';

-- 3. The stored count always equals the stored list for Lola rows.
update public.provider_tests set biomarker_count = jsonb_array_length(biomarkers_list) where provider_id = 'lola-health' and jsonb_typeof(biomarkers_list) = 'array' and jsonb_array_length(biomarkers_list) > 0;

-- 4. Price model: price = kit price, phlebotomy stored separately.
--    Single-variant products keep their price with no fees, and keep their existing collection flags.
update public.provider_tests set base_price = price, total_expected_cost = price, clinic_phlebotomy_cost = 0, home_phlebotomy_cost = 0 where provider_id = 'lola-health' and price is not null;
update public.provider_tests set price = 200, base_price = 200, total_expected_cost = 235, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'peak-insights';
update public.provider_tests set price = 155, base_price = 155, total_expected_cost = 190, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'vital-check';
update public.provider_tests set price = 125, base_price = 125, total_expected_cost = 160, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'core-health';
update public.provider_tests set price = 120, base_price = 120, total_expected_cost = 155, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'female-hormones-clarity';
update public.provider_tests set price = 145, base_price = 145, total_expected_cost = 180, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'female-active-boost';
update public.provider_tests set price = 140, base_price = 140, total_expected_cost = 175, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = false, sample_type = 'Venous' where provider_id = 'lola-health' and provider_test_id = 'male-active-boost';
update public.provider_tests set price = 110, base_price = 110, total_expected_cost = 145, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'male-hormones-clarity';
update public.provider_tests set price = 83, base_price = 83, total_expected_cost = 118, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'cardiovascular-health';
update public.provider_tests set price = 81, base_price = 81, total_expected_cost = 116, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'liver-kidney-function';
update public.provider_tests set price = 119, base_price = 119, total_expected_cost = 154, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'thyroid-hormonal-function';
update public.provider_tests set price = 89, base_price = 89, total_expected_cost = 124, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'blood-health';
update public.provider_tests set price = 95, base_price = 95, total_expected_cost = 130, clinic_phlebotomy_cost = 35, home_phlebotomy_cost = 35, clinic_visit_available = true, home_phlebotomy_option = true, home_kit_available = true, sample_type = 'Finger-prick or venous' where provider_id = 'lola-health' and provider_test_id = 'female-hormones-7';
