
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, clinical_significance, normal_range_male, normal_range_female, interpretation_guide, lifestyle_factors, related_conditions) VALUES

('Copper', 'CU', 'Minerals', 'Copper is a trace mineral involved in energy production, iron metabolism and nervous system health. It helps enzymes that support connective tissue, immunity and iron transport.', 'µmol/L', 'Copper status assessment and liver condition screening', '12-20 µmol/L', '12-20 µmol/L',
'{"high": {"description": "High copper may be due to inflammation, oestrogen therapy, liver disease or inherited conditions such as Wilson''s disease.", "urgentAdvice": "Neurological symptoms, jaundice or psychological changes with abnormal copper need prompt specialist assessment.", "improvements": ["Investigate underlying cause with specialist", "Chelation therapy may be needed for inherited disorders", "Monitor liver function"]}, "low": {"description": "Low copper can occur with poor intake, malabsorption, excessive zinc supplements or rare genetic conditions. Symptoms may include anaemia, low white blood cells, tiredness and neurological problems in severe deficiency.", "improvements": ["Dietary changes to include copper-rich foods", "Adjust zinc supplementation if excessive", "Specialist therapies under medical supervision"]}}',
ARRAY['Diet quality', 'Zinc supplementation', 'Gut health'],
ARRAY['Wilson''s disease', 'Menkes disease', 'Anaemia', 'Liver disease']),

('Iodine', 'IODINE', 'Minerals', 'Iodine is essential for thyroid hormone production, required for T3 and T4 synthesis in the thyroid gland.', 'µg/L', 'Thyroid function support and iodine status assessment', NULL, NULL,
'{"high": {"description": "Very high iodine intake, usually from supplements or contrast agents, can disturb thyroid function and cause hypo- or hyperthyroidism.", "urgentAdvice": "Neck swelling, breathing difficulty, or severe thyroid symptoms require urgent review.", "improvements": ["Reduce iodine supplement intake", "Avoid unnecessary iodine-containing products", "Monitor thyroid function"]}, "low": {"description": "Low iodine intake can lead to goitre and hypothyroidism and is especially important in pregnancy. Symptoms mirror low thyroid hormone levels (fatigue, weight gain, feeling cold).", "improvements": ["Balanced intake from iodised salt, dairy, eggs and fish", "Use supplements cautiously and only when recommended by a clinician"]}}',
ARRAY['Diet', 'Pregnancy', 'Supplement use'],
ARRAY['Goitre', 'Hypothyroidism', 'Hyperthyroidism', 'Thyroid dysfunction']),

('Vitamin A (Retinol)', 'VITA', 'Vitamins', 'Vitamin A supports vision, immunity and skin health. Retinol and its precursors like beta-carotene help the immune system, vision in dim light and healthy skin.', 'µmol/L', 'Vision, immunity and skin health assessment', NULL, NULL,
'{"high": {"description": "High vitamin A, usually from excessive supplements or liver over-consumption, can cause headache, liver damage, bone pain and birth-defect risk in pregnancy.", "urgentAdvice": "Signs of toxicity (severe headache, vomiting, confusion) or visual changes require urgent assessment.", "improvements": ["Stop high-dose supplements", "Avoid liver over-consumption", "Seek medical advice especially in pregnancy"]}, "low": {"description": "Low vitamin A can affect night vision and immunity and usually results from poor diet, fat-malabsorption or liver disease.", "improvements": ["Diet rich in dairy, eggs, oily fish and colourful vegetables", "Carefully dosed supplements when needed", "Avoid high-dose supplements without medical advice, especially in pregnancy"]}}',
ARRAY['Diet quality', 'Fat absorption', 'Liver health', 'Supplement use'],
ARRAY['Night blindness', 'Immune deficiency', 'Liver disease', 'Fat malabsorption']),

('Vitamin E', 'VITE', 'Vitamins', 'Vitamin E is an antioxidant that helps protect cells and supports immune function. It helps protect cell membranes from oxidative damage and supports skin, eye and immune health.', 'µmol/L', 'Antioxidant status and cell protection assessment', NULL, NULL,
'{"high": {"description": "High levels typically result from excessive supplements and can, at very high doses, interfere with vitamin K and clotting.", "urgentAdvice": "Unexplained neurological symptoms or bleeding issues with supplement use warrant medical review.", "improvements": ["Reduce supplement intake", "Monitor clotting function", "Assess vitamin K status"]}, "low": {"description": "Low vitamin E is rare and usually linked to fat-malabsorption or certain genetic conditions. Symptoms can include nerve and muscle damage and a weakened immune system.", "improvements": ["Dietary sources include plant oils, nuts, seeds and wheatgerm", "Supplements may be used in specific deficiency states under supervision"]}}',
ARRAY['Diet quality', 'Fat absorption', 'Supplement use'],
ARRAY['Nerve damage', 'Muscle weakness', 'Immune deficiency', 'Fat malabsorption']),

('Vitamin K', 'VITK', 'Vitamins', 'Vitamin K is essential for normal blood clotting and bone health. It helps the liver produce clotting factors and contributes to bone metabolism and calcium regulation.', NULL, 'Blood clotting and bone health assessment', NULL, NULL,
'{"high": {"description": "High vitamin K from diet is uncommon; excess synthetic forms or supplements can interfere with anticoagulant medication.", "improvements": ["Review supplement intake", "Consult clinician if on anticoagulant medication"]}, "low": {"description": "Low vitamin K can lead to easy bruising, bleeding and delayed wound healing and often relates to poor intake, malabsorption or certain medications (e.g. prolonged antibiotic use).", "urgentAdvice": "Unexplained or heavy bleeding, or very prolonged bleeding from minor injuries, needs urgent assessment.", "improvements": ["Leafy green vegetables, vegetable oils and cereal grains are good sources", "Correcting deficiency and adjusting anticoagulant doses should be guided by a clinician"]}}',
ARRAY['Diet quality', 'Antibiotic use', 'Anticoagulant medication'],
ARRAY['Bleeding disorders', 'Osteoporosis', 'Malabsorption']),

('Vitamin C (Ascorbic Acid)', 'VITC', 'Vitamins', 'Vitamin C is an antioxidant important for collagen, immunity and iron absorption. It supports skin, blood vessels, bones and cartilage.', 'µmol/L', 'Antioxidant status, collagen synthesis and iron absorption', NULL, NULL,
'{"high": {"description": "High levels usually occur from supplements; very high doses may cause stomach upset and kidney stones in susceptible people.", "improvements": ["Reduce supplement intake", "Stay hydrated", "Monitor kidney health if susceptible"]}, "low": {"description": "Low vitamin C leads to scurvy in severe cases and may cause tiredness, gum problems, bruising and poor wound healing.", "urgentAdvice": "Severe bleeding, extreme fatigue, or unexplained bruising need assessment.", "improvements": ["Increase fruit and vegetables (especially citrus, berries, peppers and leafy greens)", "Supplements can be used short-term where diet is limited"]}}',
ARRAY['Diet quality', 'Smoking', 'Fruit and vegetable intake'],
ARRAY['Scurvy', 'Poor wound healing', 'Iron deficiency anaemia', 'Kidney stones']),

('Vitamin B1 (Thiamine)', 'VITB1', 'Vitamins', 'Thiamine helps release energy from food and supports nerve and heart function. It is involved in carbohydrate metabolism and proper nerve and muscle function.', NULL, 'Energy metabolism, nerve and heart function assessment', NULL, NULL,
'{"high": {"description": "High blood levels are usually due to supplementation and are rarely harmful at typical doses.", "improvements": ["Review supplement dosage"]}, "low": {"description": "Low B1 can cause beriberi and Wernicke-Korsakoff syndrome, more common with heavy alcohol use, malnutrition or malabsorption. Symptoms include fatigue, neuropathy, confusion and heart failure in severe cases.", "urgentAdvice": "Confusion, difficulty walking, eye movement problems or heart-failure symptoms require urgent treatment.", "improvements": ["Dietary sources include whole grains, nuts, seeds, pork and fortified foods", "Supplements are often used in high-risk groups under medical guidance"]}}',
ARRAY['Alcohol intake', 'Diet quality', 'Gut health'],
ARRAY['Beriberi', 'Wernicke-Korsakoff syndrome', 'Neuropathy', 'Heart failure']),

('Vitamin B2 (Riboflavin)', 'VITB2', 'Vitamins', 'Riboflavin supports energy production, skin and eye health. It helps enzymes involved in energy metabolism and maintaining mucous membranes.', NULL, 'Energy metabolism, skin and eye health assessment', NULL, NULL,
'{"high": {"description": "High levels from supplements are usually excreted in urine and are rarely problematic.", "improvements": ["Review supplement dosage"]}, "low": {"description": "Low B2 can cause sore throat, cracked lips, mouth ulcers and skin problems.", "urgentAdvice": "Severe mouth, eye or skin symptoms with nutritional concerns warrant medical review.", "improvements": ["Include dairy, eggs, lean meat, green vegetables and fortified cereals", "Supplements can help in deficiency states"]}}',
ARRAY['Diet quality', 'Supplement use'],
ARRAY['Angular stomatitis', 'Glossitis', 'Skin disorders']),

('Vitamin B3 (Niacin)', 'VITB3', 'Vitamins', 'Niacin supports energy release and nervous system and skin health. It is involved in many metabolic reactions.', NULL, 'Energy metabolism, skin and nervous system assessment', NULL, NULL,
'{"high": {"description": "High doses from supplements or medicines can cause flushing, liver toxicity and raised blood sugar.", "urgentAdvice": "Severe skin changes, confusion or suspected overdose require urgent care.", "improvements": ["Reduce supplement intake", "Monitor liver function", "Use under medical supervision"]}, "low": {"description": "Severe deficiency causes pellagra, with dermatitis, diarrhoea and dementia. This is rare in high-income countries but can occur with malnutrition or alcoholism.", "improvements": ["Dietary sources include meat, fish, nuts, seeds and fortified grains", "Supplements should be used carefully due to side-effect risk at higher doses"]}}',
ARRAY['Diet quality', 'Alcohol intake', 'Supplement use'],
ARRAY['Pellagra', 'Liver toxicity', 'Dermatitis']),

('Vitamin B5 (Pantothenic Acid)', 'VITB5', 'Vitamins', 'Vitamin B5 helps release energy from food and synthesise hormones and fats. It is part of coenzyme A, vital for many metabolic reactions.', NULL, 'Energy metabolism and hormone synthesis assessment', NULL, NULL,
'{"high": {"description": "Excess intake from supplements is usually excreted; very high doses may cause mild digestive upset.", "improvements": ["Review supplement dosage"]}, "low": {"description": "Deficiency is rare and usually associated with severe malnutrition, causing fatigue, irritability and numbness.", "urgentAdvice": "Unexplained neurological symptoms with suspected severe deficiency need assessment.", "improvements": ["Found widely in foods such as meat, eggs, legumes, whole grains and vegetables", "A varied diet usually prevents deficiency"]}}',
ARRAY['Diet quality', 'Nutritional status'],
ARRAY['Fatigue', 'Neuropathy', 'Malnutrition']),

('Vitamin B6 (Pyridoxine)', 'VITB6', 'Vitamins', 'Vitamin B6 is important for metabolism, neurotransmitters and red blood cell production. It helps enzymes that process amino acids and supports nerve and immune function.', NULL, 'Amino acid metabolism, nerve and immune function assessment', NULL, NULL,
'{"high": {"description": "High B6 from large supplement doses can cause nerve damage and numbness.", "urgentAdvice": "New numbness, burning or weakness with heavy B6 supplementation needs urgent review.", "improvements": ["Stop or reduce high-dose supplements", "Seek neurological assessment"]}, "low": {"description": "Low B6 may cause irritability, depression, confusion, mouth problems and anaemia.", "improvements": ["Sources include poultry, fish, potatoes, bananas and fortified cereals", "Supplementation, if needed, should stay within safe limits"]}}',
ARRAY['Diet quality', 'Supplement use', 'Medication interactions'],
ARRAY['Peripheral neuropathy', 'Anaemia', 'Depression', 'Immune dysfunction']),

('Biotin (Vitamin B7)', 'VITB7', 'Vitamins', 'Biotin supports energy metabolism, skin, hair and nervous system health. It acts as a cofactor for carboxylase enzymes.', NULL, 'Energy metabolism, skin, hair and nail health assessment', NULL, NULL,
'{"high": {"description": "High supplement doses can interfere with some lab tests (including thyroid and troponin), causing misleading results.", "urgentAdvice": "Always tell clinicians about biotin supplements when having blood tests; concerning symptoms should be assessed promptly.", "improvements": ["Disclose biotin supplementation before laboratory tests", "Stop supplements 48-72 hours before blood draws if advised"]}, "low": {"description": "Deficiency is rare and can cause hair loss, skin rashes and neurological symptoms, especially in people with certain genetic disorders or high raw-egg-white intake.", "improvements": ["Biotin is found in eggs (well-cooked), nuts, seeds, whole grains and some vegetables", "Targeted supplements may be used if deficiency is confirmed"]}}',
ARRAY['Diet quality', 'Raw egg consumption', 'Genetic factors'],
ARRAY['Hair loss', 'Dermatitis', 'Neurological symptoms', 'Lab test interference']),

('Beta-Carotene', 'BCAROT', 'Vitamins', 'Beta-carotene is a plant pigment and precursor to vitamin A. It is an antioxidant found in orange and dark-green vegetables.', 'µmol/L', 'Antioxidant status and vitamin A precursor assessment', NULL, NULL,
'{"high": {"description": "High intake from foods or supplements can cause harmless yellow-orange skin (carotenemia), but very high supplement doses have been linked to harm in some smoker populations.", "improvements": ["Reduce supplement intake", "Isolated mild yellowing from diet is usually benign", "Avoid high-dose supplements if smoking"]}, "low": {"description": "Low levels may reflect low intake of fruit and vegetables or fat-malabsorption.", "improvements": ["Increase carrots, sweet potatoes, squash, apricots and dark-green leafy vegetables", "Avoid high-dose supplements unless advised"]}}',
ARRAY['Diet quality', 'Fruit and vegetable intake', 'Fat absorption', 'Smoking'],
ARRAY['Vitamin A deficiency', 'Carotenemia', 'Fat malabsorption']),

('Uric Acid', 'UA', 'Kidney Function', 'Uric acid is a breakdown product of purines and is linked to gout and kidney stones. It forms when the body breaks down purines from cells and certain foods.', 'µmol/L', 'Gout risk, kidney stone risk and metabolic health assessment', '200-430 µmol/L', '140-360 µmol/L',
'{"high": {"description": "High uric acid (hyperuricaemia) is associated with gout, kidney stones and may link to cardiovascular and metabolic risk. Causes include genetics, dietary factors, kidney impairment and some medications.", "urgentAdvice": "Sudden, severe joint pain, especially in the big toe, or flank pain with blood in urine, needs prompt assessment.", "improvements": ["Reduce purine-rich foods and alcohol", "Maintain healthy weight and hydration", "Urate-lowering drugs when needed"]}, "low": {"description": "Low levels are uncommon and usually not clinically significant, but may occur with some drugs or rare conditions.", "improvements": ["Usually no treatment needed", "Investigate if persistently low"]}}',
ARRAY['Diet', 'Alcohol intake', 'Hydration', 'Body weight', 'Medication'],
ARRAY['Gout', 'Kidney stones', 'Cardiovascular disease', 'Metabolic syndrome']),

('Homocysteine', 'HCY', 'Cardiovascular', 'Homocysteine is an amino-acid by-product; high levels are linked with cardiovascular and kidney disease risk. It is produced during methionine metabolism and is normally recycled using vitamin B12, folate and B6.', 'µmol/L', 'Cardiovascular risk and B-vitamin status assessment', '5-15 µmol/L', '5-15 µmol/L',
'{"high": {"description": "Raised homocysteine (hyperhomocysteinaemia) can result from low B12, folate or B6, kidney disease, genetic variants or certain medications and is associated with increased cardiovascular risk.", "urgentAdvice": "Acute cardiovascular or neurological symptoms (chest pain, stroke signs) need emergency care regardless of homocysteine level.", "improvements": ["Improve B12, folate and B6 intake via diet or supplements", "Manage kidney and cardiovascular risk factors"]}, "low": {"description": "Low levels are not usually a concern.", "improvements": ["No action typically needed"]}}',
ARRAY['Diet quality', 'B-vitamin intake', 'Kidney health', 'Genetic factors'],
ARRAY['Cardiovascular disease', 'Stroke', 'Kidney disease', 'B12 deficiency', 'Folate deficiency']),

('Serum Iron', 'FE', 'Iron Status', 'Serum iron measures the amount of circulating iron bound to transferrin. It reflects iron available in the bloodstream at the time of sampling.', 'µmol/L', 'Iron availability and status assessment', '10-30 µmol/L', '8-28 µmol/L',
'{"high": {"description": "High serum iron may occur in iron overload, acute iron poisoning or after supplementation.", "urgentAdvice": "Suspected iron overdose, especially in children, is an emergency.", "improvements": ["Specialist evaluation for iron overload", "Investigate underlying cause"]}, "low": {"description": "Low serum iron is seen in iron deficiency and in inflammatory conditions, so ferritin and other indices are needed for interpretation.", "improvements": ["Iron replacement therapy", "Investigate blood loss or malabsorption", "Interpret alongside ferritin and transferrin"]}}',
ARRAY['Diet quality', 'Iron supplementation', 'Blood loss', 'Inflammation'],
ARRAY['Iron deficiency anaemia', 'Iron overload', 'Haemochromatosis', 'Chronic disease anaemia']),

('Transferrin', 'TRF', 'Iron Status', 'Transferrin is the main protein that carries iron in the blood. It binds iron and transports it to tissues.', 'g/L', 'Iron transport capacity and iron status assessment', '2.0-3.6 g/L', '2.0-3.6 g/L',
'{"high": {"description": "High transferrin (or TIBC) is typical of iron deficiency.", "improvements": ["Investigate and treat iron deficiency", "Iron supplementation if deficient"]}, "low": {"description": "Low transferrin can occur in chronic disease, iron overload and liver disease; it is a negative acute-phase protein.", "urgentAdvice": "Urgency relates to underlying causes (e.g. severe anaemia or liver disease) rather than transferrin itself.", "improvements": ["Treat underlying condition", "Monitor liver function"]}}',
ARRAY['Diet quality', 'Iron intake', 'Liver health', 'Inflammation'],
ARRAY['Iron deficiency anaemia', 'Iron overload', 'Liver disease', 'Chronic disease']),

('TIBC (Total Iron-Binding Capacity)', 'TIBC', 'Iron Status', 'TIBC reflects the total capacity of blood to bind iron, largely via transferrin. It is calculated from serum iron and unsaturated iron-binding capacity.', 'µmol/L', 'Iron-binding capacity and iron status assessment', '45-80 µmol/L', '45-80 µmol/L',
'{"high": {"description": "High TIBC is typical of iron deficiency anaemia.", "improvements": ["Investigate and treat iron deficiency", "Iron supplementation if needed"]}, "low": {"description": "Low TIBC is seen in chronic disease, iron overload and some liver disorders.", "improvements": ["Treat underlying condition", "Monitor iron studies"]}}',
ARRAY['Diet quality', 'Iron intake', 'Chronic disease'],
ARRAY['Iron deficiency anaemia', 'Iron overload', 'Liver disease', 'Chronic disease']),

('Transferrin Saturation', 'TSAT', 'Iron Status', 'Transferrin saturation shows what proportion of iron-binding sites on transferrin are filled with iron. It is calculated as serum iron divided by TIBC, expressed as a percentage.', '%', 'Iron loading status and haemochromatosis screening', '20-50%', '20-50%',
'{"high": {"description": "High saturation suggests iron overload conditions like haemochromatosis or repeated transfusions.", "urgentAdvice": "Severe symptoms or suspected iron poisoning require emergency care.", "improvements": ["Phlebotomy or chelation under specialist care", "Genetic testing for haemochromatosis if appropriate"]}, "low": {"description": "Low saturation occurs in iron deficiency and also in inflammatory anaemia.", "improvements": ["Iron replacement and investigation of causes", "Interpret alongside ferritin and full blood count"]}}',
ARRAY['Diet quality', 'Iron intake', 'Blood transfusions', 'Genetic factors'],
ARRAY['Haemochromatosis', 'Iron deficiency anaemia', 'Chronic disease anaemia']),

('LDH (Lactate Dehydrogenase)', 'LDH', 'Enzymes', 'LDH is an enzyme found in many tissues and is a general marker of tissue damage. It is involved in energy metabolism and is present in heart, liver, muscles, red cells and other tissues.', 'IU/L', 'General tissue damage and cell turnover marker', '120-246 IU/L', '120-246 IU/L',
'{"high": {"description": "Raised LDH can occur with haemolysis, liver disease, muscle injury, some cancers and many other conditions. Very high levels may suggest significant tissue breakdown, such as in severe muscle injury (rhabdomyolysis).", "urgentAdvice": "Chest pain, breathlessness, severe muscle pain, dark urine or neurological symptoms with high LDH may indicate an emergency and need urgent care.", "improvements": ["Diagnose and treat the underlying condition", "LDH itself is not treated directly", "Further investigation with specific markers"]}, "low": {"description": "Low LDH is usually not clinically significant.", "improvements": ["No action typically needed"]}}',
ARRAY['Physical activity', 'Muscle health', 'Liver health'],
ARRAY['Haemolysis', 'Liver disease', 'Rhabdomyolysis', 'Cancer', 'Heart disease']);
