
INSERT INTO public.biomarkers_library (biomarker_name, biomarker_code, category, description, unit_of_measurement, clinical_significance, normal_range_male, normal_range_female, interpretation_guide, lifestyle_factors, related_conditions) VALUES

('INR (International Normalised Ratio)', 'INR', 'Haematology', 'INR is a standardised measure of blood clotting used to monitor warfarin and assess clotting disorders. It is derived from the prothrombin time and adjusts for differences between thromboplastin reagents.', NULL, 'Warfarin monitoring and clotting disorder assessment', '0.8-1.2', '0.8-1.2',
'{"high": {"description": "High INR (above target) indicates slower clotting and increased bleeding risk. Very high values can be dangerous, particularly with trauma or surgery.", "urgentAdvice": "Any serious bleeding, black stools, blood in vomit or urine, severe headache or trauma in someone with a high INR is an emergency.", "improvements": ["Anticoagulant clinic or GP will adjust warfarin dose", "Review interacting drugs and diet (vitamin K)", "Vitamin K or other treatments if INR is very high"]}, "low": {"description": "Low INR (below target) in someone on warfarin means blood is clotting more quickly than intended and clot risk may be higher.", "improvements": ["Warfarin dose adjustment", "Review dietary vitamin K intake", "Ensure compliance with medication"]}}',
ARRAY['Vitamin K intake', 'Medication compliance', 'Diet', 'Alcohol intake'],
ARRAY['Deep vein thrombosis', 'Pulmonary embolism', 'Atrial fibrillation', 'Bleeding disorders']),

('Prothrombin Time (PT)', 'PT', 'Haematology', 'PT measures how long blood takes to clot via the extrinsic and common coagulation pathways. It assesses clotting factors I, II, V, VII and X.', 'seconds', 'Bleeding disorder assessment and warfarin monitoring', NULL, NULL,
'{"high": {"description": "Prolonged PT occurs with warfarin, vitamin K deficiency, liver disease, disseminated intravascular coagulation and some rare factor deficiencies.", "urgentAdvice": "Uncontrolled or spontaneous bleeding with a prolonged PT requires urgent assessment.", "improvements": ["Vitamin K administration", "Plasma products if needed", "Adjust anticoagulants", "Treat liver or systemic disease"]}, "low": {"description": "Slightly shortened PT is usually not clinically meaningful.", "improvements": ["No action typically needed"]}}',
ARRAY['Medication use', 'Vitamin K intake', 'Liver health'],
ARRAY['Liver disease', 'Vitamin K deficiency', 'DIC', 'Factor deficiencies']),

('APTT (Activated Partial Thromboplastin Time)', 'APTT', 'Haematology', 'APTT measures clotting via the intrinsic and common pathways and is used to investigate bleeding and monitor heparin. It assesses factors VIII, IX, XI, XII and others.', 'seconds', 'Bleeding disorder investigation and heparin monitoring', NULL, NULL,
'{"high": {"description": "Prolonged APTT may reflect heparin therapy, factor deficiencies (e.g. haemophilia), lupus anticoagulant or other inhibitors.", "urgentAdvice": "Bleeding or bruising with prolonged APTT needs urgent haematology assessment.", "improvements": ["Factor replacement if deficient", "Reverse heparin if needed", "Manage autoimmune or liver disease"]}, "low": {"description": "Short APTT is usually not clinically significant.", "improvements": ["No action typically needed"]}}',
ARRAY['Medication use', 'Liver health'],
ARRAY['Haemophilia', 'Von Willebrand disease', 'Lupus anticoagulant', 'DIC']),

('Fibrinogen', 'FIB', 'Haematology', 'Fibrinogen is a clotting protein that is converted to fibrin to form blood clots. It is produced by the liver and acts both as a clotting factor and an acute-phase reactant in inflammation.', 'g/L', 'Clotting assessment and inflammation marker', '1.8-4.0 g/L', '1.8-4.0 g/L',
'{"high": {"description": "High fibrinogen reflects inflammation, infection, pregnancy or cardiovascular risk and may contribute to thrombosis.", "improvements": ["Treat underlying inflammation or infection", "Manage cardiovascular risk factors"]}, "low": {"description": "Low fibrinogen occurs in severe liver disease, DIC, congenital deficiencies or after massive bleeding. It increases the risk of serious bleeding.", "urgentAdvice": "Major bleeding, trauma or suspected DIC is an emergency.", "improvements": ["Cryoprecipitate or fibrinogen concentrate may be required", "Treat underlying cause"]}}',
ARRAY['Inflammation', 'Liver health', 'Pregnancy'],
ARRAY['DIC', 'Liver disease', 'Cardiovascular disease', 'Congenital fibrinogen disorders']),

('D-Dimer', 'DDIMER', 'Haematology', 'D-dimer is a breakdown product of fibrin and is used to help exclude blood clots such as DVT and PE. It forms when cross-linked fibrin is degraded.', 'µg/L', 'Venous thromboembolism exclusion marker', NULL, NULL,
'{"high": {"description": "Raised D-dimer is non-specific and seen in clots, infection, inflammation, trauma, surgery, pregnancy and older age.", "urgentAdvice": "Sudden breathlessness, chest pain or leg swelling require urgent assessment regardless of D-dimer level.", "improvements": ["Clinical scoring and imaging to confirm or exclude clot", "Anticoagulation for proven clots"]}, "low": {"description": "A normal D-dimer in low-risk patients can help rule out DVT or PE.", "improvements": ["No action needed"]}}',
ARRAY['Physical activity', 'Surgery', 'Pregnancy', 'Age'],
ARRAY['Deep vein thrombosis', 'Pulmonary embolism', 'DIC', 'Infection']),

('ApoB/ApoA1 Ratio', 'APOBA1', 'Lipid Profile', 'The ApoB/ApoA1 ratio compares atherogenic to protective lipoprotein particles and is used to assess cardiovascular risk. ApoB reflects harmful lipoproteins while ApoA1 reflects protective HDL particles.', NULL, 'Cardiovascular risk assessment via lipoprotein particle balance', NULL, NULL,
'{"high": {"description": "High ratios suggest more atherogenic particles relative to protective ones and increased cardiovascular risk.", "urgentAdvice": "Cardiovascular emergencies (chest pain, stroke symptoms) require urgent care regardless of ratio.", "improvements": ["Intensive lifestyle changes", "Lipid-lowering therapies targeting ApoB (e.g. statins)", "Regular exercise and weight management to raise ApoA1/HDL"]}, "low": {"description": "Low ApoB/ApoA1 ratio usually indicates a favourable lipid profile and lower risk.", "improvements": ["Maintain healthy lifestyle"]}}',
ARRAY['Diet', 'Exercise', 'Weight management', 'Smoking'],
ARRAY['Cardiovascular disease', 'Atherosclerosis', 'Metabolic syndrome']),

('High-Sensitivity CRP (hs-CRP)', 'HSCRP', 'Cardiovascular', 'Hs-CRP is a more sensitive measure of low-grade inflammation and is used in cardiovascular risk assessment. It detects chronic low-grade inflammation relevant to cardiovascular disease.', 'mg/L', 'Cardiovascular risk and low-grade inflammation assessment', '<1 mg/L (low risk)', '<1 mg/L (low risk)',
'{"high": {"description": "Sustained high hs-CRP is associated with increased cardiovascular risk and may reflect obesity, smoking, metabolic syndrome or chronic inflammatory disease.", "urgentAdvice": "Acute illness with very high CRP and systemic symptoms needs urgent care; hs-CRP alone is not for emergency decisions.", "improvements": ["Weight loss", "Exercise", "Smoking cessation", "Healthy diet", "Good control of blood pressure, lipids and glucose"]}, "low": {"description": "Low levels suggest little or no systemic inflammation.", "improvements": ["Maintain healthy lifestyle"]}}',
ARRAY['Diet', 'Exercise', 'Smoking', 'Body weight', 'Stress'],
ARRAY['Cardiovascular disease', 'Metabolic syndrome', 'Chronic inflammatory disease', 'Obesity']),

('Serum Osmolality', 'SOSM', 'Kidney Function', 'Serum osmolality reflects the concentration of dissolved particles in blood and helps assess fluid and electrolyte balance. It is influenced mainly by sodium, glucose and urea.', 'mOsm/kg', 'Fluid and electrolyte balance assessment', '275-295 mOsm/kg', '275-295 mOsm/kg',
'{"high": {"description": "High osmolality can result from dehydration, high sodium, high glucose (e.g. diabetic emergencies) or ingestion of osmotically active substances.", "urgentAdvice": "Confusion, seizures or coma with abnormal osmolality is an emergency.", "improvements": ["Careful correction of fluids and electrolytes", "Treat underlying causes, usually in hospital"]}, "low": {"description": "Low osmolality indicates over-hydration or low solute concentration, often with hyponatraemia.", "improvements": ["Fluid restriction if appropriate", "Investigate and treat underlying cause"]}}',
ARRAY['Hydration', 'Medication use', 'Diabetes management'],
ARRAY['Hyponatraemia', 'Hypernatraemia', 'Diabetic emergencies', 'Toxic alcohol ingestion']),

('Bicarbonate (HCO3)', 'HCO3', 'Kidney Function', 'Bicarbonate is an important buffer that helps maintain acid-base balance. It neutralises acids in the blood and is part of the CO2 content measured in standard biochemistry panels.', 'mmol/L', 'Acid-base balance assessment', '22-29 mmol/L', '22-29 mmol/L',
'{"high": {"description": "High bicarbonate suggests metabolic alkalosis, often from vomiting, diuretic use or chronic CO2 retention.", "improvements": ["Treat underlying cause", "Adjust medications", "Correct electrolyte imbalances"]}, "low": {"description": "Low bicarbonate indicates metabolic acidosis from causes such as kidney disease, diabetic ketoacidosis, severe diarrhoea or lactic acidosis.", "urgentAdvice": "Severe breathing difficulties, confusion or shock with acid-base disturbances need urgent care.", "improvements": ["Insulin for diabetic ketoacidosis", "Fluid and electrolyte replacement", "Adjust medications"]}}',
ARRAY['Hydration', 'Medication use', 'Kidney health', 'Diabetes management'],
ARRAY['Metabolic acidosis', 'Metabolic alkalosis', 'Diabetic ketoacidosis', 'Kidney disease']),

('Chloride', 'CL', 'Electrolytes', 'Chloride is a major electrolyte that helps maintain fluid balance and acid-base status. It works with sodium and bicarbonate and is regulated by the kidneys and hormones.', 'mmol/L', 'Fluid balance and acid-base status assessment', '98-107 mmol/L', '98-107 mmol/L',
'{"high": {"description": "High chloride can be seen in dehydration, metabolic acidosis or after saline infusions.", "urgentAdvice": "Severe symptoms related to underlying causes (e.g. dehydration, acidosis) require urgent care.", "improvements": ["Correct fluid and acid-base disturbances", "Adjust medications"]}, "low": {"description": "Low chloride may occur with vomiting, metabolic alkalosis or some diuretics.", "improvements": ["Treat underlying cause", "Adjust medications", "Correct fluid balance"]}}',
ARRAY['Hydration', 'Medication use', 'Diet'],
ARRAY['Dehydration', 'Metabolic acidosis', 'Metabolic alkalosis', 'Vomiting']),

('Phosphate', 'PHOS', 'Minerals', 'Phosphate is important for bones, teeth, energy storage and cell function. Most phosphate is in bones; blood levels are regulated by kidneys, vitamin D and parathyroid hormone.', 'mmol/L', 'Bone health, energy metabolism and mineral balance assessment', '0.8-1.5 mmol/L', '0.8-1.5 mmol/L',
'{"high": {"description": "High phosphate is often due to kidney failure, hypoparathyroidism or high intake in the context of reduced excretion.", "urgentAdvice": "Severe muscle weakness, breathing difficulty or arrhythmias with phosphate disturbance need urgent care.", "improvements": ["Dietary changes", "Phosphate binders", "Manage kidney or parathyroid disease"]}, "low": {"description": "Low phosphate may arise from poor diet, alcoholism, refeeding syndrome, hyperparathyroidism or certain medicines. Severe deficiency can cause muscle weakness, bone pain and confusion.", "improvements": ["Phosphate supplements", "Dietary changes", "Treat underlying cause"]}}',
ARRAY['Diet', 'Alcohol intake', 'Kidney health', 'Vitamin D status'],
ARRAY['Kidney failure', 'Hyperparathyroidism', 'Refeeding syndrome', 'Osteomalacia']),

('Gamma Globulins', 'GGLOBU', 'Immunology', 'Gamma globulins are the fraction of blood proteins that mainly contain immunoglobulins (antibodies). They are separated on serum protein electrophoresis and reflect antibody production.', 'g/L', 'Immune function and plasma cell disorder assessment', NULL, NULL,
'{"high": {"description": "A broad-based increase suggests polyclonal activation (infection, autoimmune disease); a sharp spike (M-band) suggests a monoclonal gammopathy like myeloma.", "urgentAdvice": "Bone pain, anaemia, recurrent infections or kidney problems with abnormal electrophoresis should prompt urgent haematology review.", "improvements": ["Investigate and treat infections or autoimmune diseases", "Haematology referral for monoclonal gammopathies"]}, "low": {"description": "Low gamma fraction can indicate immunodeficiency or protein loss.", "improvements": ["Immunology assessment", "Investigate cause of protein loss"]}}',
ARRAY['Immune health', 'Infection status'],
ARRAY['Multiple myeloma', 'MGUS', 'Immunodeficiency', 'Autoimmune disease']),

('Immunoglobulin G (IgG)', 'IGG', 'Immunology', 'IgG is the most abundant antibody class in blood and key for long-term immunity. IgG antibodies protect against infections and can indicate past exposure or vaccination.', 'g/L', 'Long-term immunity and immunodeficiency assessment', NULL, NULL,
'{"high": {"description": "High IgG can occur with chronic infection, autoimmune disease or monoclonal gammopathies.", "urgentAdvice": "Frequent or severe infections, weight loss or bone pain warrant urgent assessment.", "improvements": ["Investigate underlying cause", "Immunology or haematology referral"]}, "low": {"description": "Low IgG (hypogammaglobulinaemia) can cause recurrent infections and may be inherited or secondary to medications or diseases.", "improvements": ["Immunoglobulin replacement therapy", "Investigate and treat underlying cause"]}}',
ARRAY['Immune health', 'Medication use'],
ARRAY['Hypogammaglobulinaemia', 'Chronic infection', 'Autoimmune disease', 'Myeloma']),

('Immunoglobulin A (IgA)', 'IGA', 'Immunology', 'IgA is an antibody important at mucosal surfaces such as the gut and airways. It protects mucosal surfaces and is present in secretions like saliva and tears.', 'g/L', 'Mucosal immunity and immunodeficiency assessment', NULL, NULL,
'{"high": {"description": "Raised IgA can occur with chronic liver disease, infections and some plasma-cell disorders.", "urgentAdvice": "Serious or recurrent infections and systemic symptoms need timely evaluation.", "improvements": ["Investigate liver or haematological disease", "Monitor and treat infections"]}, "low": {"description": "Selective IgA deficiency is relatively common and can increase risk of respiratory and gut infections and some autoimmune conditions.", "improvements": ["Infection prevention and vaccination", "Investigate possible associated conditions"]}}',
ARRAY['Immune health', 'Liver health'],
ARRAY['IgA deficiency', 'Coeliac disease', 'Liver disease', 'IgA nephropathy']),

('Immunoglobulin M (IgM)', 'IGM', 'Immunology', 'IgM is the first antibody class produced in response to an infection. It appears early in immune responses and helps clear pathogens.', 'g/L', 'Acute infection response and immunodeficiency assessment', NULL, NULL,
'{"high": {"description": "High IgM can result from acute infection, autoimmune disease or IgM monoclonal gammopathies (e.g. Waldenstrom''s macroglobulinaemia).", "urgentAdvice": "Symptoms such as weight loss, night sweats, recurrent infections or bleeding should be assessed promptly.", "improvements": ["Further immunology or haematology testing", "Treatment tailored to underlying cause"]}, "low": {"description": "Low IgM may be part of broader immunodeficiency or secondary to other conditions.", "improvements": ["Immunology assessment", "Investigate underlying cause"]}}',
ARRAY['Immune health', 'Infection status'],
ARRAY['Waldenstrom''s macroglobulinaemia', 'Acute infection', 'Immunodeficiency', 'Autoimmune disease']),

('ANA (Antinuclear Antibodies)', 'ANA', 'Immunology', 'ANA detect antibodies directed against components of the cell nucleus and are used to screen for autoimmune connective tissue diseases such as lupus, Sjogren''s syndrome and mixed connective tissue disease.', NULL, 'Autoimmune connective tissue disease screening', NULL, NULL,
'{"high": {"description": "Positive ANA can be seen in autoimmune diseases, infections, some medications and even in healthy people at low titre.", "urgentAdvice": "Severe joint pain, rashes, chest pain, breathlessness or neurological symptoms need urgent assessment regardless of ANA status.", "improvements": ["Rheumatology referral for interpretation with symptoms and other tests", "Monitoring or treatment for autoimmune disease if confirmed"]}, "low": {"description": "A negative ANA makes many systemic autoimmune diseases less likely but does not completely exclude them.", "improvements": ["No action needed if asymptomatic"]}}',
ARRAY['Immune health', 'Medication use'],
ARRAY['Systemic lupus erythematosus', 'Sjogren''s syndrome', 'Mixed connective tissue disease', 'Drug-induced lupus']),

('Rheumatoid Factor (RF)', 'RF', 'Immunology', 'RF is an autoantibody used in the assessment of rheumatoid arthritis and some other conditions. It targets the Fc portion of IgG and can form immune complexes.', 'IU/mL', 'Rheumatoid arthritis and autoimmune disease assessment', NULL, NULL,
'{"high": {"description": "Raised RF can be seen in rheumatoid arthritis, other autoimmune diseases, chronic infections and some healthy older adults.", "urgentAdvice": "Severe joint swelling, fever or systemic illness requires timely assessment.", "improvements": ["Rheumatology referral for diagnosis and treatment", "Early aggressive control of inflammation"]}, "low": {"description": "Negative RF does not exclude rheumatoid arthritis but makes it less likely, especially if anti-CCP is also negative.", "improvements": ["No action needed if asymptomatic"]}}',
ARRAY['Immune health', 'Smoking', 'Age'],
ARRAY['Rheumatoid arthritis', 'Sjogren''s syndrome', 'Chronic infection', 'Cryoglobulinaemia']),

('Anti-CCP Antibodies (ACPA)', 'ACPA', 'Immunology', 'Anti-CCP (ACPA) antibodies are highly specific for rheumatoid arthritis. They target cyclic citrullinated peptides and are associated with erosive rheumatoid arthritis.', 'U/mL', 'Rheumatoid arthritis diagnosis and prognosis', NULL, NULL,
'{"high": {"description": "Positive anti-CCP strongly suggests rheumatoid arthritis and may predict more severe disease.", "urgentAdvice": "Persistent joint swelling, stiffness and pain require early rheumatology referral regardless of antibody status.", "improvements": ["Early disease-modifying treatment under rheumatology care", "Can slow joint damage and improve long-term outcomes"]}, "low": {"description": "Negative results make RA less likely but do not fully exclude it.", "improvements": ["No action needed if asymptomatic"]}}',
ARRAY['Immune health', 'Smoking'],
ARRAY['Rheumatoid arthritis', 'Erosive joint disease']),

('Albumin/Globulin (A/G) Ratio', 'AGRATIO', 'Liver Function', 'The A/G ratio compares albumin to globulin proteins in the blood and can signal liver, kidney or immune disorders. It is calculated by dividing albumin by globulin.', NULL, 'Liver, kidney and immune disorder screening', '1.0-2.5', '1.0-2.5',
'{"high": {"description": "High ratios can occur with low globulins (some immunodeficiencies) or relatively high albumin (dehydration).", "improvements": ["Investigate immunodeficiency if globulins low", "Correct dehydration"]}, "low": {"description": "Low ratios may reflect low albumin (liver disease, nephrotic syndrome, malnutrition) or high globulins (inflammation, gammopathies).", "urgentAdvice": "Urgency depends on underlying conditions such as liver failure, kidney disease or suspected myeloma.", "improvements": ["Treat liver, kidney, nutritional or immune causes", "Improved control of underlying disease"]}}',
ARRAY['Diet', 'Liver health', 'Kidney health', 'Immune health'],
ARRAY['Liver disease', 'Nephrotic syndrome', 'Multiple myeloma', 'Malnutrition']),

('Urea/Creatinine Ratio', 'UCRATIO', 'Kidney Function', 'The urea/creatinine ratio helps distinguish causes of kidney problems and assess hydration. Creatinine is a more constant marker of filtration, while urea is influenced by diet and hydration.', NULL, 'Kidney function differentiation and hydration assessment', NULL, NULL,
'{"high": {"description": "High ratios suggest dehydration, gastrointestinal bleeding or increased protein breakdown relative to kidney filtration.", "urgentAdvice": "Signs of severe dehydration, blood in stools, or very little urine need urgent assessment.", "improvements": ["Rehydration", "Investigate gastrointestinal bleeding", "Adjust protein intake"]}, "low": {"description": "Low ratios may occur in liver disease, low protein intake or some intrinsic kidney conditions.", "improvements": ["Investigate liver function", "Assess dietary protein intake", "Treat underlying kidney disease"]}}',
ARRAY['Hydration', 'Diet', 'Protein intake', 'Kidney health'],
ARRAY['Dehydration', 'Gastrointestinal bleeding', 'Liver disease', 'Chronic kidney disease']);
