// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfmxxgonjnkpfjijtjom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbXh4Z29uam5rcGZqaWp0am9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzI0NTQsImV4cCI6MjA2MzAwODQ1NH0.bW8ct-UPVLD8m1wA431gviaOw0ngbOwwhBRdpKqCI3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);