// biomarkersChunk5.ts — chunk 5 of 15 — myhealth checkup Biomarker Library
export const biomarkersChunk5 = [
  {
    id: "17-ohp", name: "17-Hydroxyprogesterone", abbr: "17-OHP", category: "Reproductive Health",
    icon: "🧬", what: "17-Hydroxyprogesterone (17-OHP) is an intermediate steroid in the adrenal cortisol synthesis pathway. When the enzyme 21-hydroxylase is deficient (congenital adrenal hyperplasia — CAH), 17-OHP accumulates to very high levels while cortisol is deficient.", why: "17-OHP is the definitive test for CAH from 21-hydroxylase deficiency — the most common form. Classic CAH causes ambiguous genitalia in newborn females and potentially life-threatening salt-wasting crises. Non-classical CAH (NC-CAH) presents in adolescence or adulthood with androgen excess. UK newborn screening includes 17-OHP.",
    unit: "nmol/L",
    ranges: { both: { normal: { range: "< 2 nmol/L (morning)", label: "Normal" }, borderline: { range: "2–10 nmol/L", label: "Borderline — Synacthen Test Required", meaning: "Intermediate range — an ACTH stimulation test is required." }, high: { range: "> 10 nmol/L", label: "Elevated — CAH Likely", meaning: "NC-CAH likely; > 30–100 nmol/L suggests classic CAH." } } },
    tips: ["Test in the early morning (8–9am) fasting.", "Women: test in the follicular phase (Days 1–7) of the cycle.", "NC-CAH is significantly underdiagnosed in women presenting with PCOS.", "UK Newborn Blood Spot screening now includes 17-OHP for early CAH detection."],
    relatedTests: ["Adrenal Hormone Panel", "Androstenedione", "DHEA-S", "Cortisol", "ACTH"],
  },
  {
    id: "urine-iodine-cr", name: "Urinary Iodine:Creatinine Ratio", abbr: "UI/Cr", category: "Iron & Nutrients",
    icon: "⚗️", what: "The urinary iodine to creatinine ratio provides a spot urine estimate of iodine status corrected for urine concentration. As 90% of dietary iodine is excreted in urine, this ratio provides reliable individual-level iodine status assessment without requiring a 24-hour collection.", why: "Iodine deficiency causes hypothyroidism and goitre and is particularly dangerous in pregnancy — even mild deficiency impairs foetal brain development and lowers child IQ. UK adults are increasingly iodine insufficient due to declining milk consumption and increasing plant-based diets.",
    unit: "µg/g creatinine",
    ranges: { both: { low: { range: "< 100 µg/g Cr", label: "Insufficient", meaning: "Iodine deficiency — thyroid stress, goitre risk, cognitive impairment risk in pregnancy." }, normal: { range: "100–300 µg/g Cr", label: "Adequate" }, high: { range: "> 400 µg/g Cr", label: "Excessive", meaning: "Excess iodine — risk of iodine-induced thyroid dysfunction in susceptible individuals." } } },
    tips: ["UK dairy products (cow's milk, yoghurt) are the main iodine sources — plant-based diets are at significant risk.", "Pregnant women should take a supplement containing 150 µg iodine (as potassium iodide — not kelp/seaweed).", "Check the thyroid (TSH, Free T4) if urinary iodine is very low or very high."],
    relatedTests: ["Thyroid Panel", "TSH", "Free T4"],
  },
  {
    id: "serum-epo", name: "Erythropoietin", abbr: "EPO", category: "Full Blood Count",
    icon: "🔴", what: "Erythropoietin (EPO) is a glycoprotein hormone produced primarily by the kidneys in response to low blood oxygen levels. It stimulates the bone marrow to produce red blood cells, increasing oxygen-carrying capacity.", why: "EPO measurement helps distinguish polycythaemia types. In polycythaemia vera (PV), EPO is suppressed. In secondary polycythaemia (from hypoxia or EPO-secreting tumours), EPO is elevated. In chronic kidney disease, EPO production is impaired, causing anaemia.",
    unit: "mIU/mL",
    ranges: { both: { low: { range: "< 2.6 mIU/mL", label: "Low/Suppressed", meaning: "Polycythaemia vera — autonomous red cell production without EPO drive. JAK2 mutation testing essential." }, normal: { range: "2.6–18.5 mIU/mL", label: "Normal" }, high: { range: "> 18.5 mIU/mL", label: "Elevated", meaning: "Secondary polycythaemia (hypoxia, sleep apnoea), EPO-secreting tumour, or EPO doping." } } },
    tips: ["EPO is the key differentiator between polycythaemia vera (low EPO) and secondary polycythaemia (high EPO).", "JAK2 V617F mutation testing should always be requested alongside EPO when PV is suspected.", "Sleep apnoea is a common and treatable cause of secondary polycythaemia."],
    relatedTests: ["Full Blood Count", "JAK2 Mutation", "Reticulocytes", "Kidney Function"],
  },
  {
    id: "non-hdl-cholesterol", name: "Non-HDL Cholesterol", abbr: "Non-HDL", category: "Cholesterol & Heart",
    icon: "❤️", what: "Non-HDL cholesterol is calculated as total cholesterol minus HDL cholesterol. It encompasses all atherogenic lipoproteins — LDL, VLDL, IDL, and remnant particles — in a single value. It is a better cardiovascular risk predictor than LDL alone because it captures all cholesterol-carrying particles contributing to atherosclerosis.", why: "Non-HDL cholesterol is recommended by NICE and ESC/EAS as a primary lipid target, particularly in patients with hypertriglyceridaemia, diabetes, or metabolic syndrome — where remnant lipoprotein cholesterol is elevated but LDL may appear deceptively normal.",
    unit: "mmol/L",
    ranges: { both: { normal: { range: "< 3.4 mmol/L", label: "Optimal" }, borderline: { range: "3.4–4.9 mmol/L", label: "Borderline High", meaning: "Moderate cardiovascular risk — lifestyle modification and risk factor assessment." }, high: { range: "> 4.9 mmol/L", label: "High", meaning: "High cardiovascular risk from combined atherogenic particle burden." } } },
    tips: ["Non-HDL target for high cardiovascular risk: < 2.5 mmol/L (NICE/ESC guidelines).", "Non-HDL can be calculated from any standard cholesterol panel without fasting.", "Non-HDL tracks well with ApoB — both measure overall atherogenic particle burden."],
    relatedTests: ["Cholesterol Panel", "LDL", "HDL", "Total Cholesterol", "ApoB", "Triglycerides"],
  },
  {
    id: "vldl", name: "VLDL Cholesterol", abbr: "VLDL", category: "Cholesterol & Heart",
    icon: "❤️", what: "VLDL (very low-density lipoprotein) is produced by the liver and transports endogenously synthesised triglycerides to peripheral tissues. As VLDL releases its triglyceride load, it becomes IDL then LDL. VLDL is calculated as triglycerides ÷ 2.2 (mmol/L).", why: "Elevated VLDL is a component of the atherogenic dyslipidaemia of metabolic syndrome — characterised by high triglycerides, high VLDL, low HDL. VLDL remnants (IDL) are directly atherogenic. VLDL overproduction is driven by liver insulin resistance and high carbohydrate intake.",
    unit: "mmol/L",
    ranges: { both: { normal: { range: "< 0.77 mmol/L", label: "Normal" }, borderline: { range: "0.77–1.5 mmol/L", label: "Borderline Elevated", meaning: "Metabolic syndrome, insulin resistance, or high refined carbohydrate diet." }, high: { range: "> 1.5 mmol/L", label: "High", meaning: "Dyslipidaemia of metabolic syndrome — associated with cardiovascular risk." } } },
    tips: ["Cutting refined carbohydrates and sugar is the most effective dietary intervention for elevated VLDL.", "Omega-3 fatty acids at high doses (3–4g EPA+DHA daily) dramatically reduce VLDL and triglycerides.", "Fibrate drugs (fenofibrate, gemfibrozil) specifically target VLDL and triglycerides."],
    relatedTests: ["Cholesterol Panel", "Triglycerides", "LDL", "Non-HDL Cholesterol", "ApoB"],
  },
  {
    id: "blood-film", name: "Peripheral Blood Film", abbr: "PBF", category: "Full Blood Count",
    icon: "🩸", what: "A peripheral blood film is a microscopic examination of a thin layer of blood stained with Wright-Giemsa dye. A haematologist visually examines red cell morphology, white cell differential, platelet characteristics, and identifies any abnormal cells. It provides qualitative information that automated analysers cannot.", why: "The blood film is the most information-rich haematological test. It can identify: schistocytes (TTP, DIC), target cells (liver disease, thalassaemia), hypersegmented neutrophils (B12/folate deficiency), blast cells (acute leukaemia), malarial parasites, sickle cells, and spherocytes.",
    unit: "Morphological report",
    ranges: { both: { stages: [
      { stage: "Normal", range: "Normochromic normocytic RBCs, no abnormal cells", meaning: "Healthy red cell morphology, no blast cells." },
      { stage: "Hypochromic microcytic", range: "Pale small RBCs", meaning: "Iron deficiency, thalassaemia, anaemia of chronic disease." },
      { stage: "Macrocytosis", range: "Large oval RBCs (macro-ovalocytes)", meaning: "B12/folate deficiency, liver disease, hypothyroidism." },
      { stage: "Schistocytes present", range: "Fragmented RBCs", meaning: "Microangiopathic haemolytic anaemia — TTP, HUS, DIC. URGENT investigation." },
      { stage: "Blast cells", range: "Immature myeloid/lymphoid cells", meaning: "Acute leukaemia — URGENT haematology referral." },
    ] } },
    tips: ["Always request a blood film when the FBC or clinical picture is unexplained.", "Blast cells on a blood film are a haematological emergency — same-day haematology review required.", "Malarial parasites can be seen on thick and thin blood films — essential in returned travellers with fever."],
    relatedTests: ["Full Blood Count", "Reticulocytes", "LDH", "Haptoglobin", "Direct Coombs Test"],
  },
  {
    id: "direct-coombs", name: "Direct Coombs Test (DAT)", abbr: "DAT", category: "Full Blood Count",
    icon: "🩸", what: "The Direct Antiglobulin Test (DAT) detects antibodies or complement proteins already bound to red blood cells in the patient's circulation. It is performed by washing the patient's red cells and adding antihuman globulin serum — agglutination indicates red cells are coated with IgG antibodies or complement.", why: "The DAT is the definitive test for autoimmune haemolytic anaemia (AIHA) — where the immune system makes antibodies against its own red cells, causing haemolysis. It also detects haemolytic disease of the newborn (HDN), drug-induced immune haemolysis, and haemolytic transfusion reactions.",
    unit: "Positive / Negative",
    ranges: { both: { normal: { range: "Negative", label: "Negative — No Red Cell Sensitisation" }, high: { range: "Positive", label: "Positive — Red Cells Coated", meaning: "Autoimmune haemolytic anaemia (AIHA), drug-induced haemolysis, haemolytic disease of newborn, or haemolytic transfusion reaction." } } },
    tips: ["Warm AIHA (IgG at 37°C) is the most common type — associated with CLL, SLE, drugs, or idiopathic.", "Cold AIHA (IgM+C3) is associated with Mycoplasma, EBV, or lymphoma.", "A negative DAT with haemolysis should prompt investigation for G6PD deficiency, hereditary spherocytosis, or PNH."],
    relatedTests: ["Haemolytic Screen", "Full Blood Count", "LDH", "Haptoglobin", "Bilirubin"],
  },
  {
    id: "jak2", name: "JAK2 V617F Mutation", abbr: "JAK2", category: "Full Blood Count",
    icon: "🩸", what: "The JAK2 V617F point mutation is a somatic gain-of-function mutation in the Janus kinase 2 gene. When mutated, JAK2 V617F causes unregulated activation of proliferation signals, leading to unchecked red cell, white cell, or platelet production independently of normal growth factor control.", why: "JAK2 V617F is present in >95% of polycythaemia vera (PV) cases and ~50–60% of essential thrombocythaemia (ET) and myelofibrosis cases. It is the defining molecular marker for myeloproliferative neoplasms (MPNs).",
    unit: "Positive / Negative",
    ranges: { both: { normal: { range: "Negative", label: "JAK2 Mutation Not Detected" }, high: { range: "Positive", label: "JAK2 V617F Mutation Detected", meaning: "Myeloproliferative neoplasm confirmed (PV, ET, or myelofibrosis). Urgent haematology referral and bone marrow biopsy required." } } },
    tips: ["All patients with unexplained erythrocytosis (raised haematocrit) should be tested for JAK2.", "Thrombocytosis with JAK2 positive = essential thrombocythaemia until proven otherwise.", "Budd-Chiari syndrome and portal vein thrombosis are strong indications for JAK2 testing.", "JAK2 inhibitors (ruxolitinib) are approved treatments for PV and myelofibrosis."],
    relatedTests: ["Full Blood Count", "EPO", "Bone Marrow Biopsy", "CALR Mutation", "MPL Mutation"],
  },
  {
    id: "vitamin-b6", name: "Vitamin B6 (Pyridoxine)", abbr: "VIT B6", category: "Iron & Nutrients",
    icon: "🌿", what: "Vitamin B6 (pyridoxine) serves as a cofactor for over 100 enzymatic reactions including amino acid metabolism, haemoglobin synthesis, neurotransmitter synthesis (serotonin, dopamine, GABA), and glycogen breakdown.", why: "B6 deficiency causes peripheral neuropathy, seborrhoeic dermatitis, depression, and a microcytic anaemia. Important to monitor in patients on isoniazid (TB medication), hydralazine, or penicillamine. B6 toxicity from high-dose supplements (> 200 mg/day) causes painful sensory neuropathy.",
    unit: "nmol/L (PLP — active form)",
    ranges: { both: { low: { range: "< 20 nmol/L", label: "Deficient", meaning: "Peripheral neuropathy, sideroblastic anaemia, depression, elevated homocysteine." }, borderline: { range: "20–30 nmol/L", label: "Borderline" }, normal: { range: "30–143 nmol/L", label: "Normal" }, high: { range: "> 200 nmol/L", label: "Elevated (Toxicity Risk)", meaning: "High-dose supplement use — chronic excess causes sensory neuropathy." } } },
    tips: ["Isoniazid (TB treatment) causes B6 deficiency — always co-prescribe B6 (pyridoxine 10–25 mg/day).", "The safe upper limit for B6 supplements is 10 mg/day in the UK (BNF) — many OTC B-complexes contain far higher doses.", "B6 is the cofactor for DOPA decarboxylase — required for both serotonin and dopamine synthesis."],
    relatedTests: ["B-Vitamin Panel", "Homocysteine", "B12", "Folate", "Full Blood Count"],
  },
  {
    id: "vitamin-b1", name: "Vitamin B1 (Thiamine)", abbr: "VIT B1", category: "Iron & Nutrients",
    icon: "🌿", what: "Thiamine (vitamin B1) acts as a cofactor for key enzymes in carbohydrate and energy metabolism — most critically pyruvate dehydrogenase and alpha-ketoglutarate dehydrogenase. The brain and peripheral nerves are acutely dependent on thiamine for energy production.", why: "Thiamine deficiency causes two serious neurological syndromes: Wernicke's encephalopathy (acute — confusion, ophthalmoplegia, ataxia — a medical emergency) and Korsakoff's syndrome (chronic — irreversible memory loss). Most common in alcohol use disorder, malnutrition, and prolonged vomiting.",
    unit: "nmol/L",
    ranges: { both: { low: { range: "< 70 nmol/L", label: "Deficient", meaning: "Risk of Wernicke's encephalopathy and Korsakoff's syndrome. Urgent IV/IM thiamine replacement required." }, borderline: { range: "70–90 nmol/L", label: "Borderline" }, normal: { range: "90–148 nmol/L", label: "Normal" } } },
    tips: ["NEVER give IV glucose to a malnourished or alcohol-dependent patient without giving thiamine first — glucose loads precipitate acute Wernicke's encephalopathy.", "Wernicke's encephalopathy is a clinical emergency — give IV thiamine (Pabrinex) before waiting for blood results.", "High-dose oral thiamine (100 mg three times daily) is used for prophylaxis in at-risk alcohol-dependent patients."],
    relatedTests: ["B-Vitamin Panel", "B12", "Folate", "Alcohol Markers (GGT)", "MCV"],
  },
  {
    id: "reverse-t3", name: "Reverse T3", abbr: "rT3", category: "Thyroid",
    icon: "🦋", what: "Reverse T3 (rT3) is a biologically inactive metabolite of T4. Under physiological stress — illness, fasting, surgery, or inflammation — the body shunts more T4 conversion toward rT3 and away from active T3, reducing cellular metabolic rate. rT3 occupies thyroid hormone receptors without activating them.", why: "An elevated rT3 with low free T3 (while TSH remains normal) occurs in significant acute or chronic illness, known as 'non-thyroidal illness syndrome' (NTIS). It may partly explain hypothyroidism-like fatigue in chronically ill or severely malnourished individuals. Its clinical utility remains debated.",
    unit: "pg/mL (pmol/L)",
    ranges: { both: { low: { range: "< 10 pg/mL", label: "Low" }, normal: { range: "10–24 pg/mL", label: "Normal" }, high: { range: "> 24 pg/mL", label: "Elevated", meaning: "Non-thyroidal illness syndrome, fasting/caloric restriction, selenium deficiency, or inflammatory illness." } } },
    tips: ["rT3 is not routinely measured in standard thyroid assessment — interpret alongside free T3 and TSH.", "Severe illness, major surgery, burns, and starvation all acutely raise rT3 — this is an adaptive response, not disease.", "Selenium deficiency impairs deiodinase enzymes, shunting T4 toward rT3."],
    relatedTests: ["Thyroid Panel", "Free T3", "Free T4", "TSH", "Selenium"],
  },
  {
    id: "calcitonin", name: "Calcitonin", abbr: "CT", category: "Thyroid",
    icon: "🦋", what: "Calcitonin is a hormone produced by the parafollicular C cells of the thyroid gland. It lowers blood calcium by inhibiting osteoclast activity. Calcitonin's primary clinical importance is as a tumour marker for medullary thyroid carcinoma (MTC).", why: "Calcitonin is the definitive tumour marker for medullary thyroid carcinoma (MTC) — a cancer arising from the C cells. MTC accounts for 3–5% of thyroid cancers and is associated with MEN2A and MEN2B syndromes (RET proto-oncogene mutations). Serial calcitonin monitoring detects MTC recurrence after surgery.",
    unit: "pg/mL",
    ranges: { male: { normal: { range: "< 11.5 pg/mL", label: "Normal" }, high: { range: "> 100 pg/mL", label: "Elevated", meaning: "Highly suggestive of medullary thyroid carcinoma. Urgent specialist review." } }, female: { normal: { range: "< 4.6 pg/mL", label: "Normal" }, high: { range: "> 4.6 pg/mL", label: "Elevated", meaning: "Medullary thyroid carcinoma, C-cell hyperplasia, or MEN2 syndrome." } } },
    tips: ["All patients with MTC and their first-degree relatives should be offered RET mutation genetic testing.", "MEN2A: MTC + phaeochromocytoma + parathyroid hyperplasia. MEN2B: MTC + phaeochromocytoma + Marfanoid habitus.", "Before thyroid surgery for nodules, calcitonin screening can detect unsuspected MTC."],
    relatedTests: ["Thyroid Panel", "CEA", "PTH", "RET Mutation Testing", "Urine Catecholamines"],
  },
  {
    id: "bile-acids", name: "Serum Bile Acids", abbr: "BA", category: "Liver & Metabolic",
    icon: "🫀", what: "Bile acids are synthesised in the liver from cholesterol and secreted into bile to aid fat digestion. They are almost completely reabsorbed and recycled. Fasting serum bile acids are normally very low — elevated levels indicate impaired hepatic extraction, reflecting early liver dysfunction.", why: "Serum bile acids are one of the most sensitive markers of hepatic function — they may be elevated when other LFT markers are still normal. Particularly important in intrahepatic cholestasis of pregnancy (ICP) — where elevated bile acids (> 40 µmol/L) indicate increased risk of stillbirth.",
    unit: "µmol/L",
    ranges: { both: { normal: { range: "< 6 µmol/L (fasting)", label: "Normal" }, borderline: { range: "6–14 µmol/L", label: "Mildly Elevated" }, high: { range: "14–40 µmol/L", label: "Elevated", meaning: "Significant hepatic dysfunction or cholestasis." }, veryHigh: { range: "> 40 µmol/L", label: "Markedly Elevated", meaning: "Intrahepatic cholestasis of pregnancy (ICP) — high stillbirth risk, early delivery indicated." } } },
    tips: ["In pregnancy, bile acids > 40 µmol/L are associated with significantly increased stillbirth risk — early delivery at 37 weeks is recommended.", "Ursodeoxycholic acid (UDCA) is first-line treatment for ICP.", "Bile acids are the most sensitive routine indicator of hepatocellular function."],
    relatedTests: ["Liver Function Tests", "ALT", "GGT", "Bilirubin", "ALP"],
  },
  {
    id: "hs-crp", name: "High-Sensitivity CRP", abbr: "hsCRP", category: "Cardiac Markers",
    icon: "💓", what: "High-sensitivity CRP (hsCRP) uses an assay detecting concentrations below 10 mg/L — detecting subtle, low-level inflammation in the range of 0.5–10 mg/L. hsCRP in the 1–10 mg/L range reflects chronic subclinical inflammation and is used as a cardiovascular risk marker.", why: "hsCRP is an independent predictor of cardiovascular events even at levels considered 'normal' on standard CRP assays. The JUPITER trial demonstrated that individuals with normal LDL but elevated hsCRP (> 2 mg/L) benefit from statin therapy. hsCRP reflects vascular inflammation contributing to atherosclerotic plaque instability.",
    unit: "mg/L",
    ranges: { both: { low: { range: "< 1.0 mg/L", label: "Low Cardiovascular Inflammatory Risk" }, borderline: { range: "1.0–3.0 mg/L", label: "Average Cardiovascular Inflammatory Risk", meaning: "Moderate subclinical inflammation — consider lifestyle optimisation." }, high: { range: "3.0–10.0 mg/L", label: "High Cardiovascular Inflammatory Risk", meaning: "Elevated vascular inflammation — strong predictor of future cardiovascular events." }, veryHigh: { range: "> 10.0 mg/L", label: "Acute Inflammation Present", meaning: "Likely acute inflammatory process — does not reflect chronic cardiovascular risk." } } },
    tips: ["hsCRP should be measured twice, 2 weeks apart, without intercurrent illness.", "Obesity is a major driver of chronically elevated hsCRP.", "hsCRP > 3 mg/L with normal LDL is an indication for statin therapy based on the JUPITER trial evidence."],
    relatedTests: ["Cardiac Risk Panel", "LDL", "Non-HDL Cholesterol", "ApoB", "Lp(a)", "HbA1c"],
  },
  {
    id: "renin-angiotensin", name: "Aldosterone:Renin Ratio", abbr: "ARR", category: "Kidney Function",
    icon: "💧", what: "The aldosterone:renin ratio (ARR) is the primary screening test for primary hyperaldosteronism (Conn's syndrome) — the most common surgically curable form of hypertension. A high ratio reflects autonomous aldosterone secretion despite low renin.", why: "Primary hyperaldosteronism affects 5–10% of all hypertensive patients and up to 20% of those with resistant hypertension — yet it is significantly under-diagnosed. It is either surgically curable (unilateral adrenal adenoma) or medically managed (bilateral hyperplasia — spironolactone).",
    unit: "pmol/L per mIU/L",
    ranges: { both: { normal: { range: "< 70 (using pmol/L ÷ mIU/L)", label: "Normal" }, high: { range: "> 70", label: "Elevated — Primary Hyperaldosteronism Suspected", meaning: "Confirmatory testing and adrenal imaging required." } } },
    tips: ["Stop spironolactone 4 weeks before, ACE inhibitors/ARBs and diuretics 2 weeks before testing.", "Hypertension + spontaneous hypokalaemia is the classic clinical clue.", "If ARR is positive: confirm with saline suppression test, then CT adrenals and adrenal vein sampling."],
    relatedTests: ["Adrenal Panel", "Aldosterone", "Renin", "Potassium", "Blood Pressure Profile"],
  },
  {
    id: "ghrelin", name: "Ghrelin", abbr: "GHRL", category: "Hormones",
    icon: "⚡", what: "Ghrelin is the 'hunger hormone' — a peptide primarily produced by specialised cells in the gastric fundus. It is the only known circulating orexigenic (appetite-stimulating) hormone. Ghrelin rises before meals (signalling hunger) and falls after eating. It also stimulates growth hormone release.", why: "Ghrelin plays a fundamental role in energy balance. High ghrelin levels are found in anorexia nervosa and severe caloric restriction — a compensatory hunger drive that makes sustained caloric restriction very difficult. GLP-1 receptor agonists (semaglutide) powerfully suppress ghrelin — explaining much of their appetite-suppressing effect.",
    unit: "pg/mL",
    ranges: { both: { low: { range: "< 100 pg/mL", label: "Low", meaning: "Postprandial state, obesity, or post-bariatric surgery." }, normal: { range: "100–450 pg/mL (fasting)", label: "Normal" }, high: { range: "> 450 pg/mL", label: "High", meaning: "Prolonged fasting, anorexia nervosa, caloric restriction, cachexia, or Prader-Willi syndrome." } } },
    tips: ["Sleep deprivation raises fasting ghrelin levels — a key mechanism by which poor sleep drives weight gain.", "Sleeve gastrectomy reduces ghrelin production by removing up to 80% of ghrelin-secreting fundal cells.", "High-protein meals suppress ghrelin more effectively than high-carbohydrate meals."],
    relatedTests: ["Metabolic Hormones Panel", "Leptin", "GLP-1", "Insulin", "IGF-1"],
  },
];
